### ISSUE TITLE
Option to run benchmarks in a folder

### ISSUE THREAD

**Issue by kunalspathak** [dotnet/BenchmarkDotNet#1423] opened 2020-04-14 18:36 UTC
I am interested in running benchmarks inside [runtime folder](https://github.com/dotnet/performance/tree/master/src/benchmarks/micro/runtime) but looks like there is no unified namespace that I can use to filter. Is there a way to specify folder or should we add namespace based on folders?  Even the [AnyCategories](https://github.com/dotnet/BenchmarkDotNet/blob/e8bf99272bc410601863bda338b57d0c46baad70/src/BenchmarkDotNet/Filters/AnyCategoriesFilter.cs#L15) and [AllCategories](https://github.com/dotnet/BenchmarkDotNet/blob/e8bf99272bc410601863bda338b57d0c46baad70/src/BenchmarkDotNet/Filters/AllCategoriesFilter.cs#L15) doesn't filter benchmarks who just has a particular category.  E.g. [Json_Net](https://github.com/dotnet/performance/blob/8aed638c9ee65c034fe0cca4ea2bdc3a68d2a6b5/src/benchmarks/micro/Serializers/Json_FromStream.cs#L89) . 

I tried with some simple regex to filter out benchmarks but apparently it didn't work.
`dotnet artifacts\MicroBenchmarks.dll --filter "BenchStone.BenchF.*|BenchStone.BenchI.*" --list tree` returned no benchmarks.

**Comment by kunalspathak** [comment] 2020-04-14 18:36
Related : https://github.com/dotnet/performance/issues/1277

**Comment by adamsitnik** [comment] 2020-04-15 08:50
could you please try:

```cmd
--filter "BenchStone.BenchF.*" "BenchStone.BenchI.*"
```

**Comment by adamsitnik** [comment] 2020-04-15 09:04
Btw if you want all the results to be joined into a single table, use `--join`

**Comment by kunalspathak** [comment] 2020-04-15 14:02
> --filter "BenchStone.BenchF.*" "BenchStone.BenchI.*"

That worked. Thanks. But some of the benchmarks in runtime folder don't have common namespace and/or no namespace. 

> Btw if you want all the results to be joined into a single table, use --join

This is super useful. Thanks for telling about that option. From last few days I was manually searching the result and putting them in excel. Single table will help me copying them easily in excel.

**Comment by adamsitnik** [comment] 2020-09-11 11:06
> But some of the benchmarks in runtime folder don't have common namespace and/or no namespace

I was thinking about this for a while. I could not find any API that would tell me at runtime to which folder the given type belonged during compilation process. Since the API is missing and the issue is specific to performance repo (using types without namespaces) I am going to close it now and mark it as "won't fix".

**Closed by adamsitnik** 2020-09-11 11:06 UTC
