### ISSUE TITLE
Dispose disposable return types

### ISSUE THREAD

**Issue by aalmada** [dotnet/BenchmarkDotNet#1788] opened 2021-08-27 18:09 UTC
To avoid dead code elimination, the result of an operation should be returned by the benchmark method. The issue is when the result should be disposed, so that non-GC resources are freed. I can use a `using` or call `Dispose()` explicitly but then the benchmark is accounting for the disposing.

Is it possible to make BDN call `Dispose()` on the returned instance if its type implements `IDisposable`?

**Comment by adamsitnik** [comment] 2021-08-30 07:54
> Is it possible to make BDN call Dispose() on the returned instance if its type implements IDisposable

It would be possible, the problem is that it would be hard to accurately measure the overhead of doing that and excluding it from the result reported by BDN. Example: if your benchmark would be creating a `FileStream`, our boilerplate code would need to create and dispose a `FileStream` instance with exactly the same arguments, otherwise it would not be accurate (some of them require more sys-calls than others).

Since you have to create and dispose the instance to perform given work that you want to benchmark, it should be OK to keep it as part of the benchmark as this code is anyway going to be included in your app. I am 99.999% sure that .NET JIT is not going to treat it as dead code even if the result is not consumed (cc @AndyAyersMS @egorbo)

```csharp
[Benchmark]
public void Some()
{
   using var instance = new SomeDisposableType();
   instance.Work();
}
```

If given instance can be reused for multiple calls, you can use `[GlobalSetup]` and `[GlobalCleanup]`.

**Comment by timcassell** [comment] 2021-08-30 08:19
> It would be possible, the problem is that it would be hard to accurately measure the overhead of doing that and excluding it from the result reported by BDN. Example: if your benchmark would be creating a `FileStream`, our boilerplate code would need to create and dispose a `FileStream` instance with exactly the same arguments, otherwise it would not be accurate (some of them require more sys-calls than others).

Using my `CleanupTarget` idea should make that feasible. Measuring the overhead then would be as simple as measuring the time it takes to call the cleanup function. The implementation would then have a choice of storing the result of each invocation and cleanup after a full iteration, or cleanup after every invocation. It could work either way, I just think the first option could be more accurate with the overhead (doesn't have to measure the actual cleanup function), while the second option saves on memory.

> Since you have to create and dispose the instance to perform given work that you want to benchmark, it should be OK to keep it as part of the benchmark as this code is anyway going to be included in your app.

This may be true, but sometimes I may want to know how much improvement I can get from a particular piece of work, without factoring in necessary setups or cleanups. Real applications don't necessarily have to do the cleanup work synchronously or in the same frame, especially now with IAsyncDisposable.

**Comment by adamsitnik** [comment] 2021-08-30 08:35
> Measuring the overhead then would be as simple as measuring the time it takes to call the cleanup function.

Due to [stopwatch resolution](https://aakinshin.net/posts/stopwatch/) and few other things BDN is trying very hard to avoid using the stopwatch to measure a single invocation. To allow for accurate nano-benchmarks, it's usually invoking the benchmark millions of times per single iteration

Some pseudocode from [How it works doc](https://benchmarkdotnet.org/articles/guides/how-it-works.html):

```csharp
// every iteration invokes the method (invokeCount / unrollFactor) times
Measurement RunIteration(Method method, long invokeCount, long unrollFactor)
{
    IterationSetup();
    MemoryCleanup();

    var clock = Clock.Start();

    for (long i = 0; i < invokeCount / unrollFactor; i++)
    {
        // we perform manual loop unrolling!!
        method(); // 1st call
        method(); // 2nd call

        method(); // (unrollFactor - 1)'th call
        method(); // unrollFactor'th call
    }

    var clockSpan = clock.GetElapsed();

    IterationCleanup();
    MemoryCleanup();

    return Measurement(clockSpan);
}
```

More context: https://github.com/dotnet/BenchmarkDotNet/pull/1157#pullrequestreview-241796273

Having said that, I am going to close the issue as we don't plan to change it. Thanks!

**Closed by adamsitnik** 2021-08-30 08:35 UTC

**Comment by timcassell** [comment] 2021-08-30 10:23
> Due to [stopwatch resolution](https://aakinshin.net/posts/stopwatch/) and few other things BDN is trying very hard to avoid using the stopwatch to measure a single invocation. To allow for accurate nano-benchmarks, it's usually invoking the benchmark millions of times per single iteration

That's why my first idea was to store the values in a collection, then pass them all to the cleanup function after the iteration loop. Measuring the method would no longer be necessary, and the overhead measurement is much cleaner (just add `stack.Push(default)` in the overhead measurement loop).

The only downside to that is the extra memory it would consume. Which, that alone could be a non-starter on some memory-constrained machines, but considering how cheap memory is these days and huge DDR5 coming soon, I don't see that as a real blocker. BDN could even make sure the invocation count doesn't go above the point where it runs out of memory for that purpose.

Actually, while writing this I realized there's another reason this wouldn't work... if the benchmark is trying to operate on a resource that only allows a single user, like a lockfile, then that would require disposing on every invocation. In that case, there's no getting around having to do it inside the benchmark, but maybe this should still be allowed for other cases? Or I guess it's just not worth the trouble when that's probably the main use case.

> Having said that, I am going to close the issue as we don't plan to change it. Thanks!

I can understand why if you've been banging your head against this problem for years! :laughing: Thanks for the discussion!
