### ISSUE TITLE
RPlotExporter does not work

### ISSUE THREAD

**Issue by pampua84** [dotnet/BenchmarkDotNet#1611] opened 2020-12-09 09:15 UTC
Hi guys, I tried to benchmark for Asp Bet Core Password Hashers, but I always get an error when trying to get the png as a result from the plot.
The program is a console application in .Net Core 3.1 and bechmark package version is 0.12.1. Here is the simple code:

```
    [MemoryDiagnoser]
    [RPlotExporter]
    [HtmlExporter]
    [CsvMeasurementsExporter(CsvSeparator.Comma)]
    public class PasswordHasherBenchmark
    {
        private readonly Argon2PasswordHasher<User> _argon2PasswordHasher = new Argon2PasswordHasher<User>();
        private readonly IPasswordHasher<User> _standardPasswordHasher = new PasswordHasher<User>(new OptionsManager<PasswordHasherOptions>(new OptionsFactory<PasswordHasherOptions>(
            new List<IConfigureOptions<PasswordHasherOptions>>
            {
                new ConfigureOptions<PasswordHasherOptions>(options => options.IterationCount = 100000)
            },new List<IPostConfigureOptions<PasswordHasherOptions>>() )));

        private readonly ScryptPasswordHasher<User> _scryptPasswordHasher = new ScryptPasswordHasher<User>();
        private readonly BCryptPasswordHasher<User> _bCryptPasswordHasher = new BCryptPasswordHasher<User>();

        private User _user;

        [GlobalSetup]
        public void Setup()
        {
            _user = new User
            {
                Email = "test@email.com",
                Password = "Password"
            };
        }

        [Benchmark]
        public string Argon2Hash()
        {
            return _argon2PasswordHasher.HashPassword(_user, _user.Password);
        }

        [Benchmark]
        public string StandardHash()
        {
            return _standardPasswordHasher.HashPassword(_user, _user.Password);
        }

        [Benchmark]
        public string BCryptHash()
        {
            return _bCryptPasswordHasher.HashPassword(_user, _user.Password);
        }

        [Benchmark]
        public string SCryptHash()
        {
            return _scryptPasswordHasher.HashPassword(_user, _user.Password);
        }
    }

    public class User
    {
        public string Email { get; set; }
        public string Password { get; set; }
    }
```

This is the BuildPlots.log

**Attaching package: 'dplyr'

The following objects are masked from 'package:stats':

    filter, lag

The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union

gdata: Unable to locate valid perl interpreter
gdata:
gdata: read.xls() will be unable to read Excel XLS and XLSX files
gdata: unless the 'perl=' argument is used to specify the location of a
gdata: valid perl intrpreter.
gdata:
gdata: (To avoid display of this message in the future, please ensure
gdata: perl is installed and available on the executable search path.)
gdata: Unable to load perl libaries needed by read.xls()
gdata: to support 'XLX' (Excel 97-2004) files.

gdata: Unable to load perl libaries needed by read.xls()
gdata: to support 'XLSX' (Excel 2007+) files.

gdata: Run the function 'installXLSXsupport()'
gdata: to automatically download and install the perl
gdata: libaries needed to support Excel XLS and XLSX formats.

Attaching package: 'gdata'

The following objects are masked from 'package:dplyr':

    combine, first, last

The following object is masked from 'package:stats':

    nobs

The following object is masked from 'package:utils':

    object.size

The following object is masked from 'package:base':

    startsWith

Attaching package: 'gridExtra'

The following object is masked from 'package:gdata':

    combine

The following object is masked from 'package:dplyr':

    combine

R.devices v2.16.1 (2019-10-24 06:00:03 UTC) successfully loaded. See ?R.devices for help.
Error: Problem with `filter()` input `..1`.
x object 'Measurement_IterationStage' not found
i Input `..1` is `Measurement_IterationStage == "Result"`.
Backtrace:
    x
 1. +-measurements %>% filter(Measurement_IterationStage == "Result")
 2. +-dplyr::filter(., Measurement_IterationStage == "Result")
 3. +-dplyr:::filter.data.frame(., Measurement_IterationStage == "Result")
 4. | \-dplyr:::filter_rows(.data, ...)
 5. |   +-base::withCallingHandlers(...)
 6. |   \-mask$eval_all_filter(dots, env_filter)
 7. \-base::.handleSimpleError(...)
 8.   \-dplyr:::h(simpleError(msg, call))
Execution halted**

**Comment by adamsitnik** [comment] 2021-02-20 20:46
Hi @pampua84 

The log that you have provided shows that the problem is not related to BenchmarkDotNet, but your config (missing perl):

```log
gdata: Unable to locate valid perl interpreter
gdata:
gdata: read.xls() will be unable to read Excel XLS and XLSX files
gdata: unless the 'perl=' argument is used to specify the location of a
gdata: valid perl intrpreter.
gdata:
gdata: (To avoid display of this message in the future, please ensure
gdata: perl is installed and available on the executable search path.)
```

Since there is nothing actionable on BDN side, I am closing the issue.

**Closed by adamsitnik** 2021-02-20 20:46 UTC
