### ISSUE TITLE
Custom NuGet Feed Credentials

### ISSUE THREAD

**Issue by benwalpole** [dotnet/BenchmarkDotNet#2586] opened 2024-07-03 08:38 UTC
Hi,

We are attempting to use BenchmarkDotNet within a project that sources NuGet packages from an internal private feed.

When BenchmarkDotNet is doing a package restore as part of the its build it is getting an authentication error when trying to connect to this feed.

When BenchmarkDotNet launches which user is is running as?
Is there a way to pass credentials for things like a NuGet feed into BenchmarkDotNet?
Is it possible to instruct BenchmarkDotNet to not do a restore as part of its build process?

**Comment by adamsitnik** [comment] 2024-07-15 11:45
Hi @benwalpole 

This is a duplicate of https://github.com/dotnet/BenchmarkDotNet/issues/1358

You could follow the steps described here: https://github.com/dotnet/BenchmarkDotNet/issues/1358#issuecomment-715481163 and see if you can provide a fix

**Closed by adamsitnik** 2024-07-15 11:45 UTC
