### ISSUE TITLE
Constructor Time Resulting In Mixed Results

### ISSUE THREAD

**Issue by luckerby** [dotnet/BenchmarkDotNet#1304] opened 2019-10-31 18:42 UTC
Under BDN v0.11.5, consider a class with 2 methods marked for benchmark, and one constructor that essentially just burns CPU time - without any bearing on the 2 methods -, as such:
```
    [DisassemblyDiagnoser(printAsm: true, printSource: true)]
    [MemoryDiagnoser]
    public class UnderTest
    {
        const int noNumbers = 10000000;  // 10 mil
        object[] sourceArray = null;

        [Benchmark]
        public void DoNothing()
        {

        }

        [Benchmark]
        public void JustDefineAnArrayList()
        {
            ArrayList arraylist = new ArrayList(noNumbers);
        }       

        public UnderTest()
        {
            Random random = new Random(1);
            sourceArray = new object[16777216];

            for (int i = 0; i < 16777216; i++)
            {
                sourceArray[i] = random.Next(10);
            }
        }
    }
```

If I run this with `BenchmarkRunner.Run<UnderTest>()` I get the results below:
![image](https://user-images.githubusercontent.com/31319583/67975294-7abcfb00-fc1c-11e9-886e-aa710b3783a1.png)

Clearly either (1) the constructor time is taken into account, or (2) BDN knows that `DoNothing` is essentially an empty method, since the results for this method are ok. The 43 ms for `JustDefineAnArrayList` are rather high based on my experience on this particular machine, but let's continue.

Let's now simply move the declaration for `sourceArray` from the class to the constructor itself. Running the benchmark again shows the time reported for the method that simply declares the ArrayList going down 10 times, yet the `DoNothing` method is still seen with a near 0 time:
![image](https://user-images.githubusercontent.com/31319583/67975556-0040ab00-fc1d-11e9-8b63-ea3b348d5924.png)

**I don't understand why the operations belonging to the constructor - which by themselves don't operate on data needed by either benchmarked method - affect the result of one of the methods but not the other (the empty one).**

Analyzing the disassembled code for the 2 methods and constructor is the same in both cases.

I'm assuming the difference is due to some dead code elimination in the "cumulative" effect of the constructor + method under benchmark (after all, from a logical standpoint `sourceArray` can be ignored when defined within the constructor itself), but since I only get the individual assembly code for each, I can't really tell.

I also don't really think BDN can tell that `DoNothing` is indeed an empty method, since it's measuring the time just as usual, coming up with 1-2 ns/op in its corresponding benchmark cycle.

Also - the GC doesn't look to take the blame on this one, at least from the number of runs: there are 6 gen2 GCs occurring for 32 ops in the case of the first set of results and 127 gen2 GCs occurring for 128 ops for the second set.

The machine itself is not under load, and the results are reproducible on this, as well as on a different machine.

**Comment by adamsitnik** [comment] 2019-10-31 19:29
Could you please share you BDN config? It looks like you are configuring BDN to run only a single iteration, which is **very bad**. Performance is never a single number, you should be comparing distributions with at least 15 iterations. 

![image](https://user-images.githubusercontent.com/6011991/67979424-83153600-fc1c-11e9-81a7-8ace2ebfcd67.png)

**Comment by adamsitnik** [comment] 2019-10-31 19:32
Could you please use the default config, re-run the benchmarks and share the results?

**Comment by luckerby** [comment] 2019-10-31 21:30
Re-running using the default config. Results are given in the same order as the original post:

![image](https://user-images.githubusercontent.com/31319583/67987377-e9f31900-fc35-11e9-8149-64cb5bc74fc5.png)

![image](https://user-images.githubusercontent.com/31319583/67987336-caf48700-fc35-11e9-8db1-347684f05a8f.png)

@adamsitnik I was getting the same results using the default config in my initial tests, but then tried different things and dropped the number of iterations to 1, since I could see that I can successfully replicate the results under the default config each time, and also needed to save time. I should have been more clear in my initial posting, sorry about that.

**Comment by luckerby** [comment] 2019-11-03 20:59
I did some profiling (dotTrace/PerfView) against the 2 scenarios and got a glimpse into what's actually going on.

Before diving into each scenario:
-  `JustDefineAnArrayList` should allocate around 38 MB on each run, equivalent to 40 mil bytes (10 mil elements x 4 bytes/int on 32-bit target platform) plus some bytes due to overhead for the internal ArrayList structures
- dotTrace will mark blocking GCs in brown

**The "slow" scenario first**, namely the one with `sourceArray` defined at the class level.
BDN choses 32 ops/iteration and starts running. A dotTrace profiling session is done while BDN is in "// BeforeActualRun", showing an overall look of what goes on:
![image](https://user-images.githubusercontent.com/31319583/68090788-ad672d80-fe80-11e9-8edf-c1185ce15c9b.png)

The memory allocations are highlighted, and the first one after the blocking GC completes is in fact a group of 6 allocations operations, as the tooltip explains. The blocking GC is in fact part of what BDN itself invokes after each iteration. Let's expand the allocation highlighted before, and see the 6 allocations in detail:
![image](https://user-images.githubusercontent.com/31319583/68090853-8eb56680-fe81-11e9-8a3c-23b8ca4e54ee.png)

So there are 6 ArrayList allocations happening one after the other, in under 2 ms. Zooming out somewhere between the last and the first snapshots shows the approximate duration of each background gen2 GC that follows each group of allocations - roughly 300 ms:
![image](https://user-images.githubusercontent.com/31319583/68090921-434f8800-fe82-11e9-9d44-05830352e46d.png)

A PerfView trace is done on a separate run, during the same "// BeforeActualRun", and yields the results below. Note the LOH size and its survival rate across generations:
![image](https://user-images.githubusercontent.com/31319583/68090964-c670de00-fe82-11e9-8404-fecf142d7228.png)

Another view showing the duration of the GCs:
![image](https://user-images.githubusercontent.com/31319583/68090980-0041e480-fe83-11e9-9be6-5b4c5802a2e2.png)

The duration of the independent GCs themselves is roughly equal, regardless if they're induced (groups of 4 on the Main thread) or background GCs (groups of 6 on the GC thread). If one sums up the allocation ticks that occur between a group of induced GCs, it adds up to 32, exactly the number of ops a BDN iteration consisted of. When averaging, the large gen2 background GCs (each in excess of 300 ms) are felt pretty hard, as the BDN results show.

_Conclusion_: There are clustered allocations performed quickly (5-6 at a time, all in under 2 ms)), followed by a lengthy gen2 background GC, which results in the high average times seen. The duration of the GCs is explained most likely by the existing 16+ mil populated `object[]` array in the LOH from the start, whose links need to be followed by the GC. There's a "clump" of allocations occurring at a time simply because there's an increased LOH budget, courtesy of the same initial populated `object[]` array.

**Now for the second scenario**, where `sourceArray` is defined at the constructor level.
BDN choses 256 ops/iteration and starts running. A similar dotTrace profiling session is done as for the first scenario, while BDN is in "// BeforeActualRun", showing an overall look of what goes on:
![image](https://user-images.githubusercontent.com/31319583/68091105-48add200-fe84-11e9-9eca-fc308956b908.png)

This time there's only one isolated allocation, followed by a gen2 background GC (which triggers a blocking ephemeral collection as well) which takes around 5 ms.

Once the 256 ops are over, BDN forces a GC, captured below as 4 distinct GCs. Note the short duration of these, as opposed to the first scenario:
![image](https://user-images.githubusercontent.com/31319583/68091160-f4572200-fe84-11e9-8925-c5e10ce319fa.png)

A PerfView trace is done on a separate run, during the same "// BeforeActualRun" (BDN crashes eventually, but works long enough to get enough data), and yields the results below. 
![image](https://user-images.githubusercontent.com/31319583/68091214-8828ee00-fe85-11e9-9aa4-74522e446753.png)

Since there are 256 ops/iteration, there's an overall majority of background gen2 GCs over the isolated ones triggered by BDN at the end of each iteration. The LOH size is close to 0, and there's nothing that gets added during the lifetime of this scenario.

_Conclusion_: Since the `sourceArray` never makes it out of the constructor, all there's allocated before each GC is an empty ArrayList, which internally translates to an empty object[] array, hence there's nothing for the GC to follow in terms of live/dead objects, so the GC is pretty fast.

There are some interesting implications based on the above: if one raises the LOH budget from the very beginning, she/he could end up with results that are faster should those artificial budget increases weren't done in the first place, provided the number of ops/iteration is chosen so that GC isn't triggered under the "inflated" budget. For the first scenario, should the number of ops would have been 5, then the only GC that would have triggered would have been the one initiated by BDN, whose time isn't counted in the results. I tried testing my assumption, but unsure how to control the number of ops/iteration (setting `unrollFactor` probably, but couldn't find a way to do it with attributes). Nonetheless, a slightly altered version of the "slow" scenario proves the point: if the function declaring the ArrayList is expanded to include a `Thread.Sleep(500)`, the results become quite interesting:
![image](https://user-images.githubusercontent.com/31319583/68091586-39318780-fe8a-11e9-8c2c-9ed059d67a3f.png)

dotTrace view over 3 consecutive iterations:
![image](https://user-images.githubusercontent.com/31319583/68091816-35ebcb00-fe8d-11e9-86db-8dd453552ff4.png)

PerfView output during "// BeforeActualRun", showing only the BDN-induced GCs at the end of each iteration:
![image](https://user-images.githubusercontent.com/31319583/68091829-5451c680-fe8d-11e9-8bdf-76331ff975be.png)

The reason for the 501 ms result is that 1 op/iteration is chosen by BDN automatically, and this time there's no more GC occurring during the function itself, since BDN's own invoked GC after each op makes sure we never quite reach the threshold required for one.

All this being said, it doesn't look like BDN is at fault here, but the GC - contrary to what I thought in the initial post. The problem is that BDN outputs the results, and without a more-than-minimum understanding of the GCs inner workings (budgets, LOH, generations etc) some of the results displayed would look flat out wrong, as shown above.

**Comment by adamsitnik** [comment] 2019-11-04 09:33
@luckerby thank you for the full explanation.

> GCs inner workings (budgets, LOH, generations etc)

This is one of the reasons why BDN runs every benchmark in a stand-alone process - to make sure that things like gen budgets and self-tuning nature of GC does not affect other benchmarks.

But when it comes to things allocated in ctor/setup and the way they affect the benchmark iterations - there is very little we can do.

**Comment by luckerby** [comment] 2019-11-06 18:04
@adamsitnik - I was thinking about some "look-at-this-tricky-sample-where-you-wouldn't-expect-these-strange-results" example mentioned somewhere in the docs. So people that benchmark and get "wrong" results because of the GC don't quickly point their finger at BDN.

A counter argument could be that if one uses BDN, it's kind of implied that she/he has some connection with the notion of performance and fine-tuning in general, which means in turn that they should already have an idea about the GC in the .NET world. And if they don't know all the nitty-gritty details, at least they're aware of the "knowns unknowns".

I was doing this - ironically - as part of looking into how much time GC takes for a specific scenario involving `ArrayList`s, and simply needed one populated to be used as source; it's then when I stumbled across this issue. And when I got to the sample involving `Sleep` and saw the results it still got me baffled with a "this can't be right" reaction. But it was only because the sample was simple and knew what the outcome should have been. Provided there were some 2 complex methods being benchmarked one against the others, I would have just looked at the results and concluded "well,  if BDN says it is so, it has to be so" particularly if both showed positive and comparable numbers in the gen0/1/2 BDN output, just as the issue in this thread did.

**Comment by adamsitnik** [comment] 2020-10-23 18:16
@luckerby thank you for a great discussion.

The harness creates an instance of a type that defines the benchmark before it starts the benchmarking. This is done by design to make sure that BDN measures only the performance of the code that is inside the `[Benchmark]` method.

We even [recommend](https://github.com/dotnet/performance/blob/master/docs/microbenchmark-design-guidelines.md#setup) our users to move the setup logic to the `ctor` or `[GlobalSetup]` method:

Since we don't plan to change it and the `Legend` that is printed below the table with the results explains all the metrics, I am going to close the issue.

Thanks,
Adam

**Closed by adamsitnik** 2020-10-23 18:16 UTC
