### ISSUE TITLE
Issue with DefaultOrderer

### ISSUE THREAD

**Issue by Romasz** [dotnet/BenchmarkDotNet#1109] opened 2019-03-19 21:03 UTC
Looks like using a _DefaultOrderer_ with policies end up with exception in my case. The benchmark is rather simple: 
```
[DryCoreJob]
[DryCoreRtJob]
[Orderer(SummaryOrderPolicy.Declared, MethodOrderPolicy.Declared)]
public class Program
{ ...
```

The summary cannot get configured order:

> Unhandled Exception: System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at BenchmarkDotNet.Reports.Summary.GetConfiguredOrdererOrDefaultOne(IEnumerable`1 configs)
   at BenchmarkDotNet.Reports.Summary..ctor(String title, ImmutableArray`1 reports, HostEnvironmentInfo hostEnvironmentInfo, String resultsDirectoryPath, TimeSpan totalTime, ImmutableArray`1 validationErrors)
   at BenchmarkDotNet.Running.BenchmarkRunnerClean.Run(BenchmarkRunInfo benchmarkRunInfo, Dictionary`2 buildResults, IResolver resolver, ILogger logger, List`1 artifactsToCleanup, String rootArtifactsFolderPath, StartedClock& runChronometer)
   at BenchmarkDotNet.Running.BenchmarkRunnerClean.Run(BenchmarkRunInfo[] benchmarkRunInfos)
   at BenchmarkDotNet.Running.BenchmarkSwitcher.RunWithDirtyAssemblyResolveHelper(String[] args, IConfig config)
   at BenchmarkDotNet.Running.BenchmarkSwitcher.Run(String[] args, IConfig config)
   at Benchmarks.Program.Main(String[] args) in C:\Current\GithubProjects\CoreFxBenchmarks\src\Benchmarks\Program.cs:line 60

**Comment by adamsitnik** [comment] 2019-03-20 17:08
Hi @Romasz 

Thank you for your bug report. It's a duplicate of #1070, which got already fixed and will be released as part of 0.11.5 soon

**Closed by adamsitnik** 2019-03-20 17:08 UTC
