### ISSUE TITLE
Consider releasing `RuntimeInformation` methods as standalone package

### ISSUE THREAD

**Issue by ob-stripe** [dotnet/BenchmarkDotNet#1078] opened 2019-02-22 14:15 UTC
Hi,

Retrieving the correct version information for the .NET runtime is [notoriously difficult](https://weblog.west-wind.com/posts/2018/Apr/12/Getting-the-NET-Core-Runtime-Version-in-a-Running-Application). This project appears to have mostly solved this problem via the methods in [`RuntimeInformation.cs`](https://github.com/dotnet/BenchmarkDotNet/blob/master/src/BenchmarkDotNet/Portability/RuntimeInformation.cs) and some other utility methods.

Would you consider releasing this as a separate library? I think it would be tremendously useful for library developers. For instance, Stripe maintains a [.NET library](https://github.com/stripe/stripe-dotnet) and gathering proper metrics about runtime versions has always proven difficult.

Thank you for your consideration!

**Comment by adamsitnik** [comment] 2019-02-23 10:43
Hi @ob-stripe 

I am sorry, but no. It would add complexity on our side without any gains for us. The code is MIT so you can just copy-paste it. 

If you believe that similar API should be exposed by the .NET Core base class library itself please create an issue in https://github.com/dotnet/corefx/ and tag me and I will ping the right people on the Team to discuss it.

It's also a duplicate of #1017

**Closed by adamsitnik** 2019-02-23 10:43 UTC

**Comment by ob-stripe** [comment] 2019-02-23 15:36
Sorry for the dupe, I did try to check if this had been requested before but obviously didn't look hard enough.

It would definitely be nice if .NET Core did make it easier to retrieve the runtime version and I might follow your suggestion, although it would only solve half the problem for libraries that also support .NET Framework.

We'll probably just go with copying the code for now. Thanks for the reply!
