### ISSUE TITLE
Define custom names for [ParamsSource] classes

### ISSUE THREAD

**Issue by JohannesDeml** [dotnet/BenchmarkDotNet#1604] opened 2020-12-02 13:57 UTC
# Problem
When using [ParamSource], the class names are often not the names that I want to use for the column entries. For example, I have the following code:
```c#
[ParamsSource(nameof(Serializers))]
public ISerializerTarget Serializer;

public IEnumerable<ISerializerTarget> Serializers => new ISerializerTarget[]
{
	new MessagePackCSharpTarget(),
	new Lz4MessagePackCSharpTarget(),
	new NetSerializerTarget(),
	new MsgPackTarget(),
	new JsonSerializerTarget(),
	new ProtobufNetTarget(),
};
```

Since the classes `MessagePackCSharpTarget` and all others are within the namespace `DotNetSerializationBenchmark` I get the following entries for the benchmark results:
|      Method |       Runtime |           Serializer | ... |
|------------ |-------------- |--------------------- |----------:|
|   **Serialize** | **.NET Core 3.1** | **DotNe(...)arget [49]** | ... |
| Deserialize | .NET Core 3.1 | DotNe(...)arget [49] | ... |
|   Serialize | .NET Core 5.0 | DotNe(...)arget [49] | ... |
| Deserialize | .NET Core 5.0 | DotNe(...)arget [49] | ... |
|   **Serialize** | **.NET Core 3.1** | **DotNe(...)arget [55]** | ... |
| Deserialize | .NET Core 3.1 | DotNe(...)arget [55] | ... |
|   Serialize | .NET Core 5.0 | DotNe(...)arget [55] | ... |
| Deserialize | .NET Core 5.0 | DotNe(...)arget [55] | ... |
|   **Serialize** | **.NET Core 3.1** | **DotNe(...)arget [52]** | ... |
| Deserialize | .NET Core 3.1 | DotNe(...)arget [52] | ... |
| ...           | ...               | ...                      |  ... |

Since everything ends with Target and the namespace is included in the name, it is not readable at all anymore. Note, that `summaryStyle.MaxParameterColumnWidth` is set to `100` and everything is within the same namespace.

## Solution define rules
Use attributes to define how classes / parameters will show up in benchmarks. e.g.
```c#
namespace DotNetSerializationBenchmark
{
	[Display(Name="JsonSerializer")]
	internal class JsonSerializerTarget : ASerializerTarget<MemoryStream>
	{
```
I think, this approach would also offer additional flexibility to customize RPlots (#1558).

## Solution change defaults
* `summaryStyle.MaxParameterColumnWidth` has an effect on the string creation for ParamSource (Is it intended to not be that way or is that a bug?)
* Don't include namespace if the class is in the same namespace as the benchmark

**Comment by adamsitnik** [comment] 2020-12-02 14:04
Hi @JohannesDeml 

BenchmarkDotNet is calling `ToString` on every parameter, so to get shorter names you can just override it:

```cs
internal class JsonSerializerTarget
{
   public override string ToString() => "JsonSerializer";
}
```

> Is it intended to not be that way or is that a bug?

this is a bug and should be fixed

**Comment by JohannesDeml** [comment] 2020-12-02 14:17
> BenchmarkDotNet is calling `ToString` on every parameter, so to get shorter names you can just override it:
> 
> ```cs
> internal class JsonSerializerTarget
> {
>    public override string ToString() => "JsonSerializer";
> }
> ```

Wow, that was a quick response! Thanks a lot for the hint, I totally missed that possibility, that indeed is a very easy fix for my problem.

As for the `summaryStyle.MaxParameterColumnWidth`: can you give me a hint where I should start searching for the bug. I would be happy to provide a PR, but it feels a bit hard to navigate around in the project.

**Comment by adamsitnik** [comment] 2020-12-02 15:37
> Wow, that was a quick response! Thanks a lot for the hint, I totally missed that possibility, that indeed is a very easy fix for my problem.

You welcome!

>  can you give me a hint where I should start searching for the bug. I would be happy to provide a PR, but it feels a bit hard to navigate around in the project.

sure! The best place to start is to look at the PR where I've introduced it: #1265 You could start by adding a failing test to https://github.com/dotnet/BenchmarkDotNet/blob/master/tests/BenchmarkDotNet.Tests/ParameterInstanceTests.cs and then debug it from the IDE.

**Comment by JohannesDeml** [comment] 2020-12-05 13:00
Thanks for the hints! I checked the tests, and the problem is not with the implementation of ParameterInstance, but with the execution order for creation of ParameterInstances and applying the config attribute.
I have the following setup:

```
[Config(typeof(BenchmarkConfig))]
public class Benchmark { ... }

public class BenchmarkConfig : ManualConfig
{
    public BenchmarkConfig()
    {
        Job baseConfig = Job.Default;
        var processableStyle = new SummaryStyle(CultureInfo.InvariantCulture, false, SizeUnit.KB, TimeUnit.Microsecond, 
            false, true, 100);
        AddExporter(new CsvExporter(CsvSeparator.Comma, processableStyle));
    }
}
```

The problem is, that `ParameterInstance.maxParameterColumnWidth` is set in its constructor, which is called, before the Config attribute is processed.

My propsal is to allow passing the summary style to ParameterInstance.

**Comment by adamsitnik** [comment] 2020-12-07 13:54
> The problem is, that `ParameterInstance.maxParameterColumnWidth` is set in its constructor, which is called, before the Config attribute is processed.

I think that the problem is that we can have `SummaryStyle` per config (set in ctor) and per exporter (not set in ctor):

```cs
public BenchmarkConfig()
    {
        var processableStyle = new SummaryStyle(CultureInfo.InvariantCulture, false, SizeUnit.KB, TimeUnit.Microsecond, 
            false, true, 100);
        AddExporter(new CsvExporter(CsvSeparator.Comma, processableStyle)); // per exporter
        SummaryStyle = processableStyle; // per config
    }
```

And I like your proposal from #1604:

>  it is possible to have different max column widths for different exporters

👍

**Closed** 2020-12-07 18:35 UTC
