### ISSUE TITLE
Accessing the private Nuget feeds

### ISSUE THREAD

**Issue by eginsjd** [dotnet/BenchmarkDotNet#1853] opened 2021-11-29 22:24 UTC
I'm trying to run BDN on a performance test project on Azure pipelines. My solution has a config file with two private sources, every time BenchmarkDotNet Runner is invoked I get dotnet restore 401 from the autogenerated script by BDN. 
Is there a way to pass the authentication token or overwrite the Nuget config for BenchmarkDotNet? 
I'm getting Nuget.Target(131, 5) error.

**Comment by adamsitnik** [comment] 2021-11-30 09:25
> Is there a way to pass the authentication token 

No unless it can be passed as an MsBuild argument (`job.With(new Argument[] { new MsBuildArgument("/p:SomeProperty=Value")})`. We don't plan to add it, but a contribution would be welcomed. This is where the `dotnet restore` command is built:

https://github.com/dotnet/BenchmarkDotNet/blob/7d5a8ff0308201cff3e48b1173585984095e44cf/src/BenchmarkDotNet/Toolchains/DotNetCli/DotNetCliCommand.cs#L138-L145

You may also check if just ignoring the 401 error would help:

https://github.com/dotnet/BenchmarkDotNet/blob/7d5a8ff0308201cff3e48b1173585984095e44cf/src/BenchmarkDotNet/Toolchains/DotNetCli/DotNetCliCommand.cs#L59-L60

> overwrite the Nuget config for BenchmarkDotNet

BDN should respect the NuGet.config file stored in the root of your repo. I am not sure about the folder where project with benchmarks is defined.

I am closing the issue as it's a duplicate of https://github.com/dotnet/BenchmarkDotNet/issues/1358

**Closed by adamsitnik** 2021-11-30 09:25 UTC
