### ISSUE TITLE
BenchmarkDotNet does not copy needed assemblies to the run folder (again?)

### ISSUE THREAD

**Issue by UbitUmarov** [dotnet/BenchmarkDotNet#2555] opened 2024-04-05 14:51 UTC
assemblies added on main project file like

```
 <ItemGroup>
   <Reference Include="OpenMetaverse">
     <HintPath>D:\opensimWork\libomv60\bin\OpenMetaverse.dll</HintPath>
   </Reference>
</ItemGroup>

```
do get copied to normal output folder, but then do not get copied to the temporary execution folder (with uuid name).
the form
<none...   to copy files to outputs, referred here on older similar issues (#946 for example) also does not work

this was working a few weeks(months?) ago, can't tell if dotnet or BenchmarkDotnet change, but clear the temporary project file does need some fix to make sure this does work again (?) 

( using last version of vs2022 on win11, and fails with dotnet6 7 8 or 9preview selected)

**Comment by timcassell** [comment] 2024-04-05 19:32
Reference includes are not currently supported (I have a PR open to add support #2508).
As for copy files to output, you can try with the latest [nightly](https://benchmarkdotnet.org/articles/guides/nuget.html#nightly) version.

**Comment by timcassell** [comment] 2024-04-07 00:18
Closing as duplicate of #1197.

**Closed by timcassell** 2024-04-07 00:18 UTC
