### ISSUE TITLE
Can this library be used with .net framework 4.6.2?

### ISSUE THREAD

**Issue by coolsj** [dotnet/BenchmarkDotNet#1370] opened 2020-02-04 16:41 UTC
If i try to install the package from nuget for a visual studio project wise target platform is .net framework 4.6.2 or higher, it throws an error saying not target assemblies found. Please guide.

**Comment by abelbraaksma** [comment] 2020-02-04 20:21
Have a look at this thread #1334, which also links to some posts from Microsoft that suggest that there may be issues, unless you upgrade to at least 4.7.2. Other links there might lead you to a solution, there's in fact a lot of discussions on several forums about this.

**Comment by adamsitnik** [comment] 2020-09-11 11:13
I am closing this as a duplicate of #1334

**Closed by adamsitnik** 2020-09-11 11:13 UTC
