### ISSUE TITLE
Benchmarkdotnet crashes when flushing the logger

### ISSUE THREAD

**Issue by olstakh** [dotnet/BenchmarkDotNet#2264] opened 2023-02-09 19:19 UTC
Hi all.
I have a simple ASP.NET web service (.net 6) with a few controllers. No external dependencies.
Benchmark test project has 4 benchmark simple tests (they start up `Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory<MyStartup>` and calling an endpoint).

Running tests command (using 0.13.4 Benchmarkdotnet version)
`dotnet run --project BenchmarkCrashRepro\BenchmarkCrashRepro.csproj -c Release --filter * --disableLogFile`

Getting a crash:
> Unhandled exception. System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.WriteLine(String value)
   at BenchmarkDotNet.Loggers.CompositeLogger.WriteLine(LogKind logKind, String text)
   at BenchmarkDotNet.Loggers.AsyncProcessOutputReader.ProcessOnOutputDataReceived(Object sender, DataReceivedEventArgs e)
   at System.Diagnostics.AsyncStreamReader.FlushMessageQueue(Boolean rethrowInNewThread)
--- End of stack trace from previous location ---
   at System.Diagnostics.AsyncStreamReader.<>c.<FlushMessageQueue>b__18_0(Object edi)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()

The crash may differ slightly (sometimes it's arithmetic overflow exception, or negative index), or it can happen one frame earlier (in StreamWriter.WriteLine). But it's always within ProcessOnOutputDataReceived

Locally for me it fails ~ 6/10 times. In ADO pipelines i've seen only one crash in ~100 runs.

I have a private github repo with repro project, if needed. Apologies if it's a dup, i did a quick search and didn't find similar issue.

**Comment by olstakh** [comment] 2023-02-22 05:17
ping

**Comment by AndreyAkinshin** [comment] 2023-02-23 11:53
@olstakh thanks for the report!

This issue occurs when the logger is accessed simultaneously from different threads. It was originally reported in #2125 and fixed in #2133. However, it seems that the issue strikes back.

@olstakh could you please share the repro so that we can investigate the problem?
cc @adamsitnik

**Comment by olstakh** [comment] 2023-02-24 07:35
@AndreyAkinshin Added you to github repo. Stripped down to a minimum. The latest callstack with provided repro is roughly the same (reproduces less often, 1/4 times locally, i added 100ms delay to a controller just in case):

`Unhandled exception. System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.IO.StreamWriter.WriteLine(String value)
   at BenchmarkDotNet.Loggers.CompositeLogger.WriteLine(LogKind logKind, String text)
   at BenchmarkDotNet.Loggers.AsyncProcessOutputReader.ProcessOnOutputDataReceived(Object sender, DataReceivedEventArgs e)
   at System.Diagnostics.AsyncStreamReader.FlushMessageQueue(Boolean rethrowInNewThread)
--- End of stack trace from previous location ---
   at System.Diagnostics.AsyncStreamReader.<>c.<FlushMessageQueue>b__18_0(Object edi)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()`

**Comment by AndreyAkinshin** [comment] 2023-02-27 16:57
At the moment, I can't reproduce the issue on my machine using the given repro.

Will try to run it in different environments under different CPU configurations.

**Comment by olstakh** [comment] 2023-02-28 08:21
Hello, @AndreyAkinshin , @adamsitnik! Sharing my notes so far on the issue:

The race condition seems to be the following:

Thread 1 -> BenchmarkDotNet.Loggers.Broker.ProcessDataBlocking (line 87) -> CompositeLogger.WriteLine
Thread 2 -> AsyncProcessOutputReader.ProcessOnOutputDataReceived -> LoggerExtensions.WriteLine -> CompositeLogger.WriteLine
So may be the same composite logger instance is used in those 2 threads, so internal loggers that compositelogger contains are accessed from 2 threads?

Going on a limb here: looking at [DotNetCliExecutor](https://github.com/dotnet/BenchmarkDotNet/blob/master/src/BenchmarkDotNet/Toolchains/DotNetCli/DotNetCliExecutor.cs) (lines 81-83), seems like same composite logger is passed to a broker and output reader, and inside broker.ProcessData a Task.Run() is called. IMO this might lead to this double access (one from broker's Task.Run and another from the AsyncProcessOutputReader).

I have a local repro, above is the summary of my current attempts to dig into this. If more specific details are needed that i can provide - please let me know.

**Comment by timcassell** [comment] 2023-02-28 09:12
`CompositeLogger` is itself thread-safe by nature of the `ImmutableHashSet`, so it's likely one of the wrapped loggers that is not safe causing the issue (looking at `StreamLogger`, `AccumulationLogger`, and `LogCapture`).

With that information, I want to say that each logger implementation should guarantee thread-safety, rather than a simple lock around the call. Of course, that also means if a user provides a custom logger, the synchronization responsibility would fall on them (we could wrap it in a synchronized logger to add some safety).

**Comment by AndreyAkinshin** [comment] 2023-02-28 11:14
@olstakh thanks for your help with the investigation!

@timcassell It seems that all engine-related BenchmarkDotNet classes/methods use an instance of `CompositeLogger` (including `AsyncProcessOutputReader` and `Broker`). What if we wrap all of the calls of child loggers with a lock? It looks like a good interlayer to provide thread safety for an arbitrary logger (without forcing users to support thread safety in all kinds of custom loggers).
@adamsitnik what do you think?

**Comment by timcassell** [comment] 2023-02-28 11:25
If that's used everywhere, then yeah that sounds like a good solution to me. That even has the added benefit of passing the logs to all child loggers in the same order.

**Comment by timcassell** [comment] 2023-02-28 11:29
> @timcassell It seems that all engine-related BenchmarkDotNet classes/methods use an instance of `CompositeLogger` (including `AsyncProcessOutputReader` and `Broker`).

Is that a shared instance? If they each create a separate instance, it won't solve the issue.

**Comment by AndreyAkinshin** [comment] 2023-02-28 11:41
> Is that a shared instance?

Theoretically, yes, it should be the same instance created [here](https://github.com/dotnet/BenchmarkDotNet/blob/b264718949c2fc8c5882c8743b8bc5d365914130/src/BenchmarkDotNet/Running/BenchmarkRunnerClean.cs#L56).

**Comment by adamsitnik** [comment] 2023-02-28 13:41
@AndreyAkinshin is right, the only `ILogger` that is actually used by the engine is a single instance of `CompositeLogger`

It seems that I've tried to be too smart in https://github.com/dotnet/BenchmarkDotNet/pull/2133#issuecomment-1269510437 and it did not work well.

I've sent https://github.com/dotnet/BenchmarkDotNet/pull/2278

**Comment by AndreyAkinshin** [comment] 2023-02-28 13:53
@adamsitnik thanks for the fix, looks good to me, approved.

**Closed** 2023-02-28 16:29 UTC
