### ISSUE TITLE
BenchmarkDotNet does not copy needed assemblies to the run folder (again? Take2)

### ISSUE THREAD

**Issue by UbitUmarov** [dotnet/BenchmarkDotNet#2575] opened 2024-05-23 13:08 UTC
Problem as reported in #2555 and older reports, persists.
The mentioned PR that was supposed to fix it  seems forgotten or ignored.

**Comment by timcassell** [comment] 2024-06-07 19:47
#2555 was closed as a duplicate of #1197. Continuing to open new duplicate issues doesn't help. You can add your feedback in the original issue or the open PR.

**Closed by timcassell** 2024-06-07 19:47 UTC
