### ISSUE TITLE
Complete different result for same build

### ISSUE THREAD

**Issue by leandromoh** [dotnet/BenchmarkDotNet#1663] opened 2021-03-05 18:15 UTC
Sometimes I run the `Benchmark.exe` , produced by Visual Studio, 2 times or more followed and get much different results. 
Specially in "Mean" collumn.
Any reason for that? 

## First execution

``` ini

BenchmarkDotNet=v0.12.1, OS=Windows 10.0.18363.1379 (1909/November2018Update/19H2)
Intel Core i7-8650U CPU 1.90GHz (Kaby Lake R), 1 CPU, 8 logical and 4 physical cores
.NET Core SDK=5.0.103
  [Host]        : .NET Core 5.0.3 (CoreCLR 5.0.321.7212, CoreFX 5.0.321.7212), X64 RyuJIT
  .NET Core 3.1 : .NET Core 3.1.12 (CoreCLR 4.700.21.6504, CoreFX 4.700.21.6905), X64 RyuJIT
  .NET Core 5.0 : .NET Core 5.0.3 (CoreCLR 5.0.321.7212, CoreFX 5.0.321.7212), X64 RyuJIT


```
|                      Method |           Job |       Runtime | LimitRecord |       Mean |     Error |      StdDev |     Median |       Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------------------------- |-------------- |-------------- |------------ |-----------:|----------:|------------:|-----------:|------------:|------:|------:|----------:|
|      FixedLength_String_Raw | .NET Core 3.1 | .NET Core 3.1 |      500000 | 2,799.6 ms | 368.98 ms | 1,087.95 ms | 3,215.7 ms | 115000.0000 |     - |     - | 457.52 MB |
|    FixedLength_Span_Builder | .NET Core 3.1 | .NET Core 3.1 |      500000 | 1,009.0 ms | 166.36 ms |   490.50 ms | 1,052.7 ms |  11000.0000 |     - |     - |  44.56 MB |
|        FixedLength_Span_Raw | .NET Core 3.1 | .NET Core 3.1 |      500000 |   379.2 ms |   6.75 ms |     5.27 ms |   377.1 ms |  15000.0000 |     - |     - |  59.77 MB |
|   VariableLength_String_Raw | .NET Core 3.1 | .NET Core 3.1 |      500000 | 2,081.3 ms | 358.61 ms | 1,057.36 ms | 1,473.2 ms | 158000.0000 |     - |     - | 628.65 MB |
| VariableLength_Span_Builder | .NET Core 3.1 | .NET Core 3.1 |      500000 |   557.0 ms |   3.45 ms |     4.94 ms |   557.0 ms |  13000.0000 |     - |     - |  54.04 MB |
|     VariableLength_Span_Raw | .NET Core 3.1 | .NET Core 3.1 |      500000 |   541.4 ms |   6.48 ms |     5.06 ms |   540.6 ms |  17000.0000 |     - |     - |  71.13 MB |
|      FixedLength_String_Raw | .NET Core 5.0 | .NET Core 5.0 |      500000 |   910.0 ms |   5.22 ms |     4.08 ms |   910.7 ms | 107000.0000 |     - |     - | 423.95 MB |
|    FixedLength_Span_Builder | .NET Core 5.0 | .NET Core 5.0 |      500000 |   361.2 ms |  15.59 ms |    44.72 ms |   343.4 ms |  10000.0000 |     - |     - |  43.42 MB |
|        FixedLength_Span_Raw | .NET Core 5.0 | .NET Core 5.0 |      500000 |   353.4 ms |   4.27 ms |     3.56 ms |   353.2 ms |  14000.0000 |     - |     - |  58.62 MB |
|   VariableLength_String_Raw | .NET Core 5.0 | .NET Core 5.0 |      500000 | 1,218.7 ms |   6.06 ms |     5.67 ms | 1,219.7 ms | 151000.0000 |     - |     - | 597.78 MB |
| VariableLength_Span_Builder | .NET Core 5.0 | .NET Core 5.0 |      500000 |   510.5 ms |   5.41 ms |     5.31 ms |   509.8 ms |  13000.0000 |     - |     - |  52.99 MB |
|     VariableLength_Span_Raw | .NET Core 5.0 | .NET Core 5.0 |      500000 |   503.5 ms |   1.86 ms |     1.74 ms |   503.7 ms |  17000.0000 |     - |     - |  70.08 MB |

## Second execution

``` ini

BenchmarkDotNet=v0.12.1, OS=Windows 10.0.18363.1379 (1909/November2018Update/19H2)
Intel Core i7-8650U CPU 1.90GHz (Kaby Lake R), 1 CPU, 8 logical and 4 physical cores
.NET Core SDK=5.0.103
  [Host]        : .NET Core 5.0.3 (CoreCLR 5.0.321.7212, CoreFX 5.0.321.7212), X64 RyuJIT
  .NET Core 3.1 : .NET Core 3.1.12 (CoreCLR 4.700.21.6504, CoreFX 4.700.21.6905), X64 RyuJIT
  .NET Core 5.0 : .NET Core 5.0.3 (CoreCLR 5.0.321.7212, CoreFX 5.0.321.7212), X64 RyuJIT


```
|                      Method |           Job |       Runtime | LimitRecord |       Mean |    Error |    StdDev |     Median |       Gen 0 |     Gen 1 | Gen 2 | Allocated |
|---------------------------- |-------------- |-------------- |------------ |-----------:|---------:|----------:|-----------:|------------:|----------:|------:|----------:|
|      FixedLength_String_Raw | .NET Core 3.1 | .NET Core 3.1 |      500000 | 1,278.5 ms | 47.11 ms | 124.93 ms | 1,220.1 ms | 115000.0000 |         - |     - | 457.53 MB |
|    FixedLength_Span_Builder | .NET Core 3.1 | .NET Core 3.1 |      500000 |   399.8 ms |  2.23 ms |   2.09 ms |   400.5 ms |  11000.0000 |         - |     - |  44.57 MB |
|        FixedLength_Span_Raw | .NET Core 3.1 | .NET Core 3.1 |      500000 |   434.1 ms | 11.82 ms |  34.29 ms |   418.8 ms |  15000.0000 |         - |     - |  59.77 MB |
|   VariableLength_String_Raw | .NET Core 3.1 | .NET Core 3.1 |      500000 | 1,674.0 ms | 33.43 ms |  88.65 ms | 1,624.5 ms | 158000.0000 |         - |     - | 628.66 MB |
| VariableLength_Span_Builder | .NET Core 3.1 | .NET Core 3.1 |      500000 |   592.0 ms |  4.35 ms |   3.86 ms |   591.9 ms |  13000.0000 | 1000.0000 |     - |  54.09 MB |
|     VariableLength_Span_Raw | .NET Core 3.1 | .NET Core 3.1 |      500000 |   578.2 ms |  3.79 ms |   5.79 ms |   575.7 ms |  17000.0000 |         - |     - |  71.13 MB |
|      FixedLength_String_Raw | .NET Core 5.0 | .NET Core 5.0 |      500000 | 1,031.8 ms | 10.80 ms |   9.02 ms | 1,029.9 ms | 107000.0000 |         - |     - | 423.96 MB |
|    FixedLength_Span_Builder | .NET Core 5.0 | .NET Core 5.0 |      500000 |   365.6 ms |  3.21 ms |   7.10 ms |   364.0 ms |  10000.0000 |         - |     - |  43.42 MB |
|        FixedLength_Span_Raw | .NET Core 5.0 | .NET Core 5.0 |      500000 |   390.0 ms |  3.17 ms |   5.13 ms |   388.8 ms |  14000.0000 |         - |     - |  58.62 MB |
|   VariableLength_String_Raw | .NET Core 5.0 | .NET Core 5.0 |      500000 | 1,330.0 ms | 17.83 ms |  25.00 ms | 1,320.6 ms | 151000.0000 |         - |     - | 597.78 MB |
| VariableLength_Span_Builder | .NET Core 5.0 | .NET Core 5.0 |      500000 |   554.8 ms |  7.82 ms |  12.85 ms |   550.8 ms |  13000.0000 |         - |     - |  52.99 MB |
|     VariableLength_Span_Raw | .NET Core 5.0 | .NET Core 5.0 |      500000 |   537.7 ms |  5.26 ms |   7.38 ms |   534.9 ms |  17000.0000 |         - |     - |  70.08 MB |

**Comment by adamsitnik** [comment] 2021-03-08 10:06
> Any reason for that?

There are many reasons why it might be happening. Some of them:
* code|memory alignment changes
* various heuristics (like Tiered JIT not promoting given method to Tier 1)
* OS (other busy processes taking over the resources, CPU scheduling)
* hardware (disk, CPU cache)

To find out why, you need to use a profiler, capture two trace files and compare them. You can do that by using [PerfView](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md#Identifying-Regressions). If this won't give you the answer you might need to use [VTune](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md#When-to-use) or `uProf` to get the disassembly.

Since there is nothing actionable on the BDN side I am going to close this issue.

**Closed by adamsitnik** 2021-03-08 10:06 UTC
