### ISSUE TITLE
Attributes put on base methods are not considered in derived class

### ISSUE THREAD

**Issue by smitpatel** [dotnet/BenchmarkDotNet#495] opened 2017-07-18 01:03 UTC
```C#
class Program
{
    static void Main(string[] args)
    {
        BenchmarkRunner.Run<Derived>();
    }
}

public abstract class Base
{
    protected int SleepTime;

    [IterationSetup]
    public abstract void Setup();
        
    [Benchmark]
    public void Test()
    {
        Thread.Sleep(SleepTime);
    }
}

public class Derived : Base
{
    //[IterationSetup]
    public override void Setup()
    {
        SleepTime = 100;
    }
}
```
In above code I have annotated method `Base.Setup` with `IterationSetup`. When I override the method to provide implementation in derived class but don't put attribute (assuming it will come from base class automatically), then the method is not called. This makes SleepTime = `default(int)` which is 0. 
If I put attribute in derived class then it sets proper value.
Without attribute in derived class
```
Method |     Mean |    Error |   StdDev |
------- |---------:|---------:|---------:|
   Test | 164.9 ns | 3.194 ns | 3.802 ns |
```
With attribute in derived class
```
 Method |     Mean |     Error |    StdDev |
------- |---------:|----------:|----------:|
   Test | 100.5 ms | 0.0955 ms | 0.0893 ms |
```

The framework should consider attributes put on base methods.

**Comment by adamsitnik** [comment] 2017-07-25 07:33
hi @smitpatel !

Thanks for a good report. I think that you are right, the expected behavior is different than what we have today.

@AndreyAkinshin do you agree? It should be easy to implement

**Comment by AndreyAkinshin** [comment] 2017-07-25 10:27
@adamsitnik, LGTM.

**Comment by lukasz-pyrzyk** [comment] 2017-08-02 06:33
@AndreyAkinshin can you assign it to me? 

I have done it locally, but I think of a suitable unit test.

**Comment by AndreyAkinshin** [comment] 2017-08-02 06:47
@lukasz-pyrzyk, assigned.

A short note about unit tests: usually we check such stuff via integration tests which is wrong (we do because it's the easiest way). The main problem here is that it significantly increases the total time of the whole test suite (especially for .NET Core profile).
In fact, we should introduce tests which build the benchmark sets via our API (based on the class description) and check it manually (instead of parsing logs in integration tests).

**Closed** 2017-08-02 10:05 UTC
