### ISSUE TITLE
BenchmarkDonNet in CI process

### ISSUE THREAD

**Issue by hbrzostowski** [dotnet/BenchmarkDotNet#1095] opened 2019-03-08 10:42 UTC
Hi,

I have a problem with running benchmark tests in CI process. My configuration is a little bit weird but it worked until I updated benchmarkdotnet from version 10 to 11. Here is my set up:
1. I have configured TeamCity to run powershell script file which invoke WebApi controller(through POST method)
2. WebApi runs dotnet file(earlier it run exe file) using C#:
```c#
 ProcessStartInfo startInfo = new ProcessStartInfo
            {
                FileName = "dotnet",
                UseShellExecute = true,
                WorkingDirectory = workingDirectory,
                Arguments = someArguments
            };
```
3. If everything is ok, the tests are run but opposite to benchmarkdotnet version 10 I had to copy whole project code to machine where I run tests(different than TeamCity build agent. I've tried to run tests with InLine process but they too much time and they crashed). I also had to add App pool user to administrator group as it couldn't restore nuget packages while building project.

How do you suggest to set up benchmark tests in CI process ?

**Comment by Ky7m** [comment] 2019-03-08 23:28
Hi @hbrzostowski , did you try to use BenchmarkDotNet as a global tool https://benchmarkdotnet.org/articles/guides/global-dotnet-tool.html ? Does it make sense in your scenario?

**Comment by hbrzostowski** [comment] 2019-03-11 11:45
Hi @Ky7m , I've tried. When I run it with global tool I get error about dependencies(even if they are in the same directory).

**Comment by wojtpl2** [comment] 2019-03-19 08:33
@hbrzostowski 
1. Could you reproduce your exception in a small console application and share source code? Or maybe you can create a unit test which reproduces this problem?
2. I made dependencies loading feature in the global tool. Could you reproduce this exception too?

**Comment by adamsitnik** [comment] 2020-10-23 20:51
No repro has been provided since March 2019, I am closing

**Closed by adamsitnik** 2020-10-23 20:51 UTC
