### ISSUE TITLE
Benchmark fails to run when AssemblyName is different from csproj name on netcoreapp1.1 project

### ISSUE THREAD

**Issue by smitpatel** [dotnet/BenchmarkDotNet#498] opened 2017-07-21 00:30 UTC
Following guide from here
http://benchmarkdotnet.org/Overview.htm

Create a new project named `ConsoleApp1` targeting netcoreapp1.1
Follow tutorial above to add benchmarks to it. All works fine when you run it.
Now modify csproj to have following (Notice `AssemblyName` attribute having different name than csproj (ConsoleApp1.csproj)
```XML
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp1.1</TargetFramework>
    <AssemblyName>Benchmarks</AssemblyName>
  </PropertyGroup>
```
`dotnet run` fails with 
```
 Exception: System.NotSupportedException: Unable to find Benchmarks in C:\Users\smpatel\Source\Repos\ConsoleApp1 and its subfolders. Most probably the name of output exe is different than the name of the .(c/f)sproj
   at BenchmarkDotNet.Toolchains.CsProj.CsProjGenerator.GetProjectFilePath(Type benchmarkTarget, ILogger logger)
   at BenchmarkDotNet.Toolchains.CsProj.CsProjGenerator.GenerateProject(Benchmark benchmark, ArtifactsPaths artifactsPaths, IResolver resolver, ILogger logger)
   at BenchmarkDotNet.Toolchains.GeneratorBase.GenerateProject(Benchmark benchmark, ILogger logger, String rootArtifactsFolderPath, IConfig config, IResolver resolver)

```

Same thing works fine with net461 as tfm.

The executable created for net461 is named `ConsoleApp.exe`
The dll created for netcoreapp1.1 is named `Benchmarks.dll`

**Comment by AndreyAkinshin** [comment] 2017-07-21 07:38
@adamsitnik, could you take a look?

**Comment by adamsitnik** [comment] 2017-07-21 07:48
Hi!

This is by design, as you can see we have even a dedicated message for that:

`Most probably the name of output exe is different than the name of the .(c/f)sproj`

Why is that? We need to somehow find the csproj file that we want to reference. At the time of benchmark execution we know only the name of the assembly that defines benchmarks. This is why we search for csproj/fsproj with exact same name. If it's not found, we display the error message you got.

It's not a problem for .NET 4.6 because we are using Roslyn to compile for  it, so we don't generate any csproj. For .NET Core we do.

My suggestion is that you should just rename the whole `.csproj` and don't use `<AssemblyName>` attribute for the project that defines benchmarks.

I am going to close the issue right now, please feel free to reopen it if you have better idea for finding the csproj.

**Closed by adamsitnik** 2017-07-21 07:48 UTC

**Comment by smitpatel** [comment] 2017-07-21 23:31
@adamsitnik - That's what I suspected. Thanks for info.

**Comment by adamsitnik** [comment] 2018-05-02 18:37
Hello @Mike-EEE !

BDN generates a new project, with reference to the `.csproj` file which defines the benchmarks.
\
So to run the  benchmarks on the other machine  you also need to copy the code ;)

If you don't/can't do that they you can use our `[InProcessToolchain]` ([docs](http://benchmarkdotnet.org/Configs/Toolchains.htm#cs)) which does everything inside the same process.

**Comment by adamsitnik** [comment] 2018-05-03 15:28
thank you for the kind words!

You also need to check the histograms implemented by @AndreyAkinshin  in 0.10.14. This feature rocks!

**Comment by Mike-EEE** [comment] 2018-05-03 16:01
Yeah I was noticing that earlier this morning, VERY cool.  Also admiring how you have gone about implementing different concepts in general.  You have got to be in my top tier now of development heroes.  Not just in your design approach but what you have done for the community as a whole.  I think everyone is starting to gain more appreciation/awareness around performance and all the issues that involve this problem space.  Lots of awesome going on here.

**Comment by soerenwolfers** [comment] 2022-09-05 15:04
Are there any disadvantages to the `[InProcessToolchain]` attribute (e.g., will the tests run slower)? I can't figure out a way to make things work without it (renaming the csproj is not an option in the shared codebase I'm working on).

**Comment by soerenwolfers** [comment] 2022-09-05 15:22
In fact, the benchmark I just kicked off with `[InProcessToolchain]` just came back 10 minutes later saying running the test took too long. The test should have taken a few seconds, to this seems to be broken for me too.

Renaming a `.csproj` file seems like an extreme measure. Is there really no way to simply specify the csproj file manually?
