### ISSUE TITLE
Use one parameter as a baseline for others?

### ISSUE THREAD

**Issue by bbrk24** [dotnet/BenchmarkDotNet#2342] opened 2023-06-26 13:25 UTC
The documentation for baselines says to use `[Benchmark(Baseline = true)]` for baselines. Would it be possible to set a specific parameter value as the baseline instead?

I can't use multiple benchmark methods, since the value is needed to perform some setup that I don't want to be timed -- something like this:

```cs
public class ExampleBenchmark
{
  [Params(0, 100, 1000)]
  public int CacheSize { get; set; }

  [GlobalSetup]
  public void SetUpCache() =>
    AllocateCache(CacheSize);

  [Benchmark]
  public void Benchmark() =>
    DoSomethingWithCache();

  // ...
}
```

I can't allocate the cache in the benchmark method, since it's not relevant to what I'm trying to measure and how long it takes is more variable than the rest of the code. Yet, if I want to ensure that the cache matters -- e.g. use `CacheSize=0` as the baseline and see that `CacheSize=1000` runs faster -- it seems like I have to.

Would it be possible to support making the baseline a certain parameter value?

**Comment by YegorStepanov** [comment] 2023-06-26 13:36
https://github.com/dotnet/BenchmarkDotNet/issues/881:
> No, there is no way to do that as of today. 

API proposals: https://github.com/dotnet/BenchmarkDotNet/issues/431 https://github.com/dotnet/BenchmarkDotNet/issues/654 Would such APIs be useful to you?

**Comment by bbrk24** [comment] 2023-06-26 13:48
Yes, this is a duplicate of #881. As I understand it, the API proposed in #431 would be helpful, but #654 would be less beneficial for our use-case.

**Comment by adamsitnik** [comment] 2023-06-30 11:15
Closing as a duplicate of #881, let's keep the discussion going on there.

**Closed by adamsitnik** 2023-06-30 11:15 UTC
