### ISSUE TITLE
BenchmarkDotNet with non-[csproj,fsproj,vbproj] build environment?

### ISSUE THREAD

**Issue by robertblaketaylor** [dotnet/BenchmarkDotNet#2113] opened 2022-09-21 03:56 UTC
I work in an equivalent make system that does not rely on csproj or other projects types as part of the build, but am interested in leveraging BenchmarkDotNet. With some hacking got to the point where the benchmark would execute, but hung up on logic that requires a proper project file to have been created (which doesn't/wont ever exist in the build environment).

Is this a hard requirement for BenchmarkDotNet?

Observed enforcement of this requirement (CsProjGenerator.cs):

```
 [PublicAPI]
        protected virtual FileInfo GetProjectFilePath(Type benchmarkTarget, ILogger logger)
        {
            if (!GetSolutionRootDirectory(out var rootDirectory) && !GetProjectRootDirectory(out rootDirectory))
            {
                logger.WriteLineError(
                    $"Unable to find .sln or .csproj file. Will use current directory {Directory.GetCurrentDirectory()} to search for project file. If you don't use .sln file on purpose it should not be a problem.");
                rootDirectory = new DirectoryInfo(Directory.GetCurrentDirectory());
            }

            // important assumption! project's file name === output dll name
            string projectName = benchmarkTarget.GetTypeInfo().Assembly.GetName().Name;

            // I was afraid of using .GetFiles with some smart search pattern due to the fact that the method was designed for Windows
            // and now .NET is cross platform so who knows if the pattern would be supported for other OSes
            var possibleNames = new HashSet<string> { $"{projectName}.csproj", $"{projectName}.fsproj", $"{projectName}.vbproj" };
            var projectFile = rootDirectory
                .EnumerateFiles("*.*", SearchOption.AllDirectories)
                .FirstOrDefault(file => possibleNames.Contains(file.Name));

            if (projectFile == default(FileInfo))
            {
                throw new NotSupportedException(
                    $"Unable to find {projectName} in {rootDirectory.FullName} and its subfolders. Most probably the name of output exe is different than the name of the .(c/f)sproj");
            }
            return projectFile;
        }
```

**Comment by adamsitnik** [comment] 2022-09-26 08:01
Hi @robertblaketaylor 

I am sorry but it's not supported by design. 

However, you could:

- use the [InProcessToolchain](https://benchmarkdotnet.org/articles/samples/IntroInProcess.html#sample-introinprocess) which does not generate a new project, but instead emits IL and runs all the benchmarks in the same process (it should be OK as long as your benchmarks don't have side effects).
- Create a single `.csproj` file, add benchmarks there and reference `.dll` in explicit way.
- implement your own `IToolchain` that takes care of generating, building and running the code. You would need to implement one class that derives from `GeneratorBase` (to generate a project file, whatever it is in your case), one class that implements `IBuilder` and most likely reuse existing `Executor` for running the code.

Since we don't plan to implement it in the next few years, I am going to close the issue. However, if you would like to implement the support, we would be happy to review your PR and include such support in BDN (as long as your build system is not 100% specific to your company and not available outside of it).

Thanks,
Adam

**Closed by adamsitnik** 2022-09-26 08:01 UTC
