### ISSUE TITLE
Benchmarking fails when ran without internet.

### ISSUE THREAD

**Issue by CatGirlsAreLife** [dotnet/BenchmarkDotNet#1047] opened 2019-02-03 23:31 UTC
When I try to benchmark a library of mine that has no internet when it tries to do the building x exes it will fail because it will try to run a nuget restore.

**Comment by danmosemsft** [comment] 2019-02-04 07:22
Once it has restored successfully once, it works without internet presumably? I am not sure how it could do better.

**Comment by adamsitnik** [comment] 2019-02-04 11:00
Hi @CatGirlsAreLife 

@danmosemsft is right, we need to do it only once in online mode, after that dotnet restore should be able to restore everything from the cache even in the offline mode

the workaround is to use our [InProcessToolchain](https://benchmarkdotnet.org/articles/configs/toolchains.html#sample-introinprocess) which does not generate new project but runs the benchmarks in the same process

I am going to close this issue since it's more or less "by design".

**Closed by adamsitnik** 2019-02-04 11:00 UTC

**Comment by CatGirlsAreLife** [comment] 2019-02-04 19:31
Alright thanks, oh and will benchmarking be affected if I did

```cmd
git stash
git pull
git stash pop
```
or if I commit what I want (excluding benchmark generated files) and then pull and push the replayed commits?

**Comment by adamsitnik** [comment] 2019-02-07 06:12
@CatGirlsAreLife I think that as long as you don't add new NuGet dependencies it should be fine. The best way to test it would be to pull off the ethernet plug/disable wifi and give it a try. Personally, I perform such "test" before I fly anywhere to make sure I can do some coding on the plane.
