### ISSUE TITLE
Is it possible to set OperationsPerInvoke dynamically

### ISSUE THREAD

**Issue by swtrse** [dotnet/BenchmarkDotNet#2631] opened 2024-09-03 20:28 UTC
Hi,

I did run into a little problem.
The design with attributes has some drawbacks. In my case it leads to massive code duplication.
To simplify the problem let's say you have a benchmark class like this
```
public class MyBenchmark
{
    [Params(0, 100, 1000)] public override int MyParam { get; set; }

    [IterationSetup]
    public void A_Iteration_Setup()
    {
        DoSomeSetupThatIsNeededAndCantBeDoneInGlobalSetup();
    }

    [Benchmark(OperationsPerInvoke = 1000)]
    public override int MyBenchmark()
    {
	for(int i = 0; i < 1000; ++i) RunSingleBenchmark(i);
    }
}
```
The for loop based on the documentation and the warnings if you run the benchmark without it is necessary for the Benchmark to run more that 100ms, so that the Benchmark is valid.

So far so good. But now we assume MyParam does have a direct impact on the runtime of RunSingleBenchmark.
So lets say
RunSingleBenchmark with MyParams 0 runs ~0.1ms
RunSingleBenchmark with MyParams 100 runs ~50ms
RunSingleBenchmark with MyParams 1000 runs ~1000ms
DoSomeSetupThatIsNeededAndCantBeDoneInGlobalSetup for 1000 Operations needs 30 Seconds
DoSomeSetupThatIsNeededAndCantBeDoneInGlobalSetup for 100 Operations needs 3 Seconds
DoSomeSetupThatIsNeededAndCantBeDoneInGlobalSetup for 1 Operations needs 0.3 Seconds

That will lead to a very long Benchmark runtime for a single class benchmark roughly:
3*8*30000ms + 1000*6*0.1ms + 1000*6*50ms + 1000*6*1000ms =7020600ms ~117Minutes

On the other hand, if I could define OperationsPerInvoke based on MyParams the runtime would be
8*30000ms + 8*3000ms + 8*300ms + 1000*6*0.1ms + 2*6*50ms + 1*6*1000ms = 273600ms ~5 Minutes

My current solution to this is to copy the benchmark class and create separated classes for each MyParamvalue and with individual Operations per Invoke. However, if I have to change something in the benchmark class, it is a pain in the ass to copy these changes to the other benchmark classes to and it feels kind of unnecessary.

Is there some other way to set the OperationsPerInvoke beside in the Benchmark attribute?

**Comment by timcassell** [comment] 2024-09-03 20:33
Dupe of #258

**Closed by timcassell** 2024-09-03 20:33 UTC
