### ISSUE TITLE
Advanced Exception Handling

### ISSUE THREAD

**Issue by BanksySan** [dotnet/BenchmarkDotNet#373] opened 2017-02-26 22:05 UTC
W.R.T. this [StackOverflow question](http://stackoverflow.com/q/42426982/442351).

I have a scenario where I get intermittent exceptions.  At present, these exceptions either stop the run (if I allow them to bubble up) or are included in the statistics (if I wrap them in a `try-catch`).

It would be very useful to be able to analyse exceptions separately.

* View statistics with and without exceptions included.
* View summaries of exception counts

Very advanced... 

* View the state of the system during the run.
  * Timings of individual runs to spot grouping of exceptions.
  * View system details, e.g. memory, CPU, disk IO etc. to aid debugging.

**Comment by adamsitnik** [comment] 2020-10-23 21:57
No progress since 2017 and it's rather not within the scope of a microbenchmarks library. I am closing the issue.

**Closed by adamsitnik** 2020-10-23 21:57 UTC
Labels: enhancement, help wanted, up-for-grabs

**Comment by mbatms** [comment] 2020-11-12 17:23
Would you consider reopening this? The feature could be as simple as this: let there be a dedicated exception type, let's say `ExpectedException`, that, when thrown, wouldn't crash the process, just tell BDN to ignore and possibly retry that particular run.
The use case: I have a benchmark that calls an HTTP endpoint that refuses the connection sporadically. I want these failures ignored instead of crashing and invalidating the whole benchmark.

**Comment by mbatms** [comment] 2020-11-12 17:24
To clarify: I would then catch the expected exception and throw an `ExpectedException` instead.

**Comment by adamsitnik** [comment] 2020-11-12 17:26
Hi @mbatms 

> Would you consider reopening this?

**Comment by adamsitnik** [comment] 2020-11-12 17:28
Hi @mbatms 

> Would you consider reopening this?

No, because it's not within the scope of the microbenchmark harness.

You should most probably use a different tool that was designed for HTTP benchmarking like [wrk](https://github.com/wg/wrk) or [bombardier](https://github.com/codesenberg/bombardier)

Thanks,
Adam

**Comment by mbatms** [comment] 2020-11-12 17:29
Is there any way of telling BDN to ignore a particular benchmark run?

**Comment by adamsitnik** [comment] 2020-11-12 18:01
> Is there any way of telling BDN to ignore a particular benchmark run?

No, but BDN implements outliers removal so if the given run takes much more time than others then it will be excluded from the results.

**Comment by mbatms** [comment] 2020-11-13 10:41
So how do I make sure that it does remove a benchmark run? Even if I could magically make up the right delay, this would be a giant hack. Will you accept a PR?

**Comment by adamsitnik** [comment] 2020-11-13 11:10
@mbatms why don't you want to use tools that were designed for HTTP benchmarking and have been heavily adopted by not only .NET but also go, C++, and Java communities?

**Comment by mbatms** [comment] 2020-11-13 11:48
I'm not specifically benchmarking HTTP clients or servers, but some components that - among other things - make web requests, and sadly, some requests just fail randomly. I'm trying to compare performance of different implementations that connect to the same service. I should probably mock all network services, but right now I just want to see if there's significant difference between my client implementations. In later iterations I would do more fine-grained benchmarking. This is a growing solution that heavily utilizes BDN, and it would be inconvenient to use a different benchmarking tool just for this project.

**Comment by adamsitnik** [comment] 2020-11-20 13:19
@mbatms thank you for a full explanation. Have you considered adding a retry mechanism to the component that makes web requests? I understand your current needs, but I am really not eager to add any kind of exception handling to BenchmarkDotNet as it was simply designed to benchmark CPU-bound code that has no side effects.
