### ISSUE TITLE
BenchmarkDotNet add concurrent invoke mode is my greatest wish of my life🌚.

### ISSUE THREAD

**Issue by Dogwei** [dotnet/BenchmarkDotNet#1470] opened 2020-06-09 03:46 UTC
Now, Run benchmark test and I can play the game all morning🌚.
![微信截图_20200609114756](https://user-images.githubusercontent.com/14845492/84103972-1c27ed00-aa47-11ea-8ac8-b7d0d98969d1.png)

**Comment by adamsitnik** [comment] 2020-10-21 14:12
Hi @Dogwei 

This is a duplicate of #147, please follow it for updates.

BTW If BenchmarkDotNet runs benchmarks on all your CPU cores you won't be able to play any games at the same time ;p

**Closed by adamsitnik** 2020-10-21 14:12 UTC
