### ISSUE TITLE
Generic benchmarks in one report 

### ISSUE THREAD

**Issue by migoldfinger** [dotnet/BenchmarkDotNet#2599] opened 2024-07-30 12:26 UTC
Hi,
I want to generate a report that show the performance difference between  the different data types I generated a generic benchmarkclass for this,, it ends everytime with the benchmarks written in several files and not all benchmarks in one file and one table,  how can I do that.

**Comment by adamsitnik** [comment] 2024-07-30 13:46
Hi @migoldfinger 

From https://benchmarkdotnet.org/articles/samples/IntroJoin.html?q=join#sample-introjoin:

>  use the `--join` option (or `BenchmarkSwitcher.RunAllJoined`)

Remember that in order to get command line arguments respected you need to pass `args` to `BenchmarkSwitcher/Runner`

**Comment by swtrse** [comment] 2024-07-30 20:14
@adamsitnik  No NOT closed

If I use --join I got this error.
//    * You use JoinSummary options, but provided configurations cannot be joined. Only one Orderer per benchmark cases is allowed.

The reason is as soon as I add a second GenericTypeArgumentsAttribute to the class this error appears. So --join is not solution at and and your provides solution is invalid.

**Comment by migoldfinger** [comment] 2024-07-30 20:18
@adamsitnik No NOT closed

If I use --join I got this error.
// * You use JoinSummary options, but provided configurations cannot be joined. Only one Orderer per benchmark cases is allowed.

The reason is as soon as I add a second GenericTypeArgumentsAttribute to the class this error appears. So --join is no solution at all and your provides solution is invalid.

**Comment by migoldfinger** [comment] 2024-07-30 20:29
Just do be clear it seams that --join is not compatible with GenericTypeArgumentsAttribute and ConfigAttribute in combination.
Looks like there is a bug in the system with that combination.
If I remove the ConfigAttribute it works as expected.

**Comment by timcassell** [comment] 2024-07-31 05:39
@migoldfinger Can you please share your code for a repro?

**Comment by swtrse** [comment] 2024-07-31 20:29
Easy!
Works with ether Generic Benchmark.
Just clone **https://github.com/mjebrahimi/DotNet-Collections-Benchmark.git**


Change line 19 in Program.cs to
`var benchmarkInfo = BenchmarkAutoRunner.SwitcherRun(typeof(Program).Assembly, args).GetBenchmarkInfo().ToArray();`

Try to run with `--join --filter *`

**Comment by migoldfinger** [comment] 2024-07-31 20:31
@timcassell
Easy!
Works with every Generic Benchmark every time.
Just clone for example https://github.com/mjebrahimi/DotNet-Collections-Benchmark.git

Change line 19 in Program.cs to (just adding the args)
var benchmarkInfo = BenchmarkAutoRunner.SwitcherRun(typeof(Program).Assembly, args).GetBenchmarkInfo().ToArray();

Try to run with --join --filter *

**Comment by timcassell** [comment] 2024-08-05 04:49
@migoldfinger So, the error message tells you the issue.

> Only one Orderer per benchmark cases is allowed.

I took a look at your code and saw this.

```cs
[CategoriesColumn]
[MemoryDiagnoser(displayGenColumns: false)]
[Config(typeof(CustomConfig))]
#if RELEASE
[ShortRunJob]
//[SimpleJob(BenchmarkDotNet.Engines.RunStrategy.Throughput)]
#else
[MarkdownExporterAttribute.GitHub]
#endif
public class BenchmarkBase
```

I assume all your benchmark classes are inheriting from this base class. The issue is the `[Config(typeof(CustomConfig))]` becomes a separate config on each benchmark class (and on each generic instantiation of your generic benchmark class) which all get merged together. It worked when I removed that attribute from the class. I tried applying the attribute to the assembly instead, but I still hit the error. I _think_ you could fix it by instead passing it in to the benchmark runner, but I couldn't try it with your code (I have no idea how your `BenchmarkAutoRunner` is working, visual studio experience is poor).

**Comment by timcassell** [comment] 2024-08-05 04:55
@AndreyAkinshin Is that config merge working as expected? Or is there a bug in the validation? I would expect applying a single config to the assembly would succeed at least.

**Comment by AndreyAkinshin** [comment] 2024-08-26 18:44
@timcassell, thanks for the investigation! This was a "by design" behavior, but now I feel that this is completely wrong.

## Background

This problem emerges due to the unfortunate `Config` design. Right now, it mixes both "how to execute benchmarks" and "how to present results." The "how to execute" part is often scoped to a single benchmark or benchmark class; it's not a problem when different benchmark subsets have different "how to execute" descriptions. The "how to present" part is supposed to be applied for the whole summary table, but now can be configured individually for each benchmark class. When we join benchmark classes with different "how to present" descriptions, we cannot merge unambiguously. Here is a minimal repro for the current problem:


```cs
public class Config : ManualConfig
{
    public Config() => Orderer = new DefaultOrderer();
}

[Config(typeof(Config))]
public class BenchBase;

[DryJob]
public class Bench1 : BenchBase
{
    [Benchmark]
    public void Foo() { }
}

[DryJob]
public class Bench2 : BenchBase
{
    [Benchmark]
    public void Foo() { }
}

public class Program
{
    public static void Main()
    {
        BenchmarkSwitcher.FromTypes([typeof(Bench1), typeof(Bench2)]).Run(["--join", "--filter", "*"]);
    }
}
```

Two benchmark classes `Bench1` and `Bench2` get their own instances of `Config` with different instances of `Orderer` (can't be merged via Distinct). We cannot decide which `Orderer` to use in the summary table and, therefore, we fail with the following message:

```
// Validating benchmarks:
//    * You use JoinSummary options, but provided configurations cannot be joined. Only one Orderer per benchmark cases is allowed.
```

## Long-term approach

I want to completely split the configuration of execution and presentation on the API level, so that it would be impossible to create such controversal situations. It's a part of my long-lasting refactoring I'm working on in background. Unfortunately, it turned out to be more challenging than I though in the beginning: we have two many "mixtures" of logic and presentation. It seems that it would be impossible to merge everything at once, so my current strategy is to try to backport small parts of my grand refactiring one-by-one.

## Short-term solution

I feel it will be absolute OK to just disable this validation (remove `ConfigCompatibilityValidator`) and patch the logic of how we choose `Order` and `SummaryStyle` in the joined case:

```patch
diff --git a/src/BenchmarkDotNet/Reports/Summary.cs b/src/BenchmarkDotNet/Reports/Summary.cs
--- a/src/BenchmarkDotNet/Reports/Summary.cs    (revision a58872b82739b14935217adfa25db209d4419f4f)
+++ b/src/BenchmarkDotNet/Reports/Summary.cs    (date 1724696441775)
@@ -152,7 +152,7 @@
                    .Where(config => config.Orderer != DefaultOrderer.Instance)
                    .Select(config => config.Orderer)
                    .Distinct()
-                   .SingleOrDefault()
+                   .FirstOrDefault()
                ?? DefaultOrderer.Instance;
 
         private static SummaryStyle GetConfiguredSummaryStyleOrDefaultOne(ImmutableArray<BenchmarkCase> benchmarkCases)
@@ -165,7 +165,7 @@
 #nullable enable
                    .Select(benchmark => benchmark.Config.SummaryStyle)
                    .Distinct()
-                   .SingleOrDefault()
+                   .FirstOrDefault()
                ?? SummaryStyle.Default;
     }
 }
```

Effectively, instead of failing with validation message, we will correctly run all the benchmarks and present the summary table using the first provided `Orderer` and `SummaryStyle`.

@timcassell what do you think?

**Comment by timcassell** [comment] 2024-08-26 18:51
Sounds good to me. Perhaps the validation could be changed to a warning instead of removing altogether, in case someone does accidentally use 2 different orderers with different logic.

**Comment by AndreyAkinshin** [comment] 2024-08-26 19:46
@timcassell I think we can go without warnings. Reasons:
1. If the user is satisfied with the summary table style/ordering, we don't have any problems. If the user is not satisfied with the summary table style/ordering (because they provided inconsistent configs for various benchmarks), they will notice the problem without warnings. I don't see any cases, in which such a warning will be actually useful.
2. Long-term, we don't need such a warning because we aim to achieve such an API that would not allow controversial setups. Thus, if we introduce such a warning, it will still be eliminated eventually, but meanwhile, we are supposed to maintain it. I'm OK with temporary solutions while I see actual benefits, but I don't like to introduce them "just in case."

**Closed** 2024-08-27 20:18 UTC
Labels: question, Area:Validators
