### ISSUE TITLE
Is it possible to build on one machine and execute benchmarks on different, without SDK?

### ISSUE THREAD

**Issue by MaxShoshin** [dotnet/BenchmarkDotNet#2414] opened 2023-08-22 14:02 UTC
Hi!

Is it possible to run benchmarks on machine without .NET SDK?
I know about InProcess mode, but may be somehow I can generate and compile actual benchmark executables on one machine and run them on different machine without installed .NET SDK?  

Thanks!

**Comment by timcassell** [comment] 2023-08-25 02:05
I don't think this is possible currently. Theoretically it would be possible to build a standalone host process along with the child benchmark processes and package them together, but not every OS allows spawning child processes (like iOS). It's probably not worth it to try to support it.

Is there a reason you can't just install dotnet sdk on the target machine (assuming it's a desktop OS)?

**Comment by adamsitnik** [comment] 2023-08-25 04:55
Hi @MaxShoshin 

It is not. BenchmarkDotNet generates boilerplate code and we simply have to compile it. As you have noticed `InProcessToolchain` does not have this requirement (it emits IL on the fly and runs the benchmarks in dedicated threads).

Since this is by design and we don't plan to change it, I am going to close the issue.

If it's ever going to change then it will be https://github.com/dotnet/BenchmarkDotNet/issues/1770 so you can subscribe for updates.

**Closed by adamsitnik** 2023-08-25 04:55 UTC
Labels: question

**Comment by MaxShoshin** [comment] 2023-08-25 09:19
Hi @timcassell 

> Is there a reason you can't just install dotnet sdk on the target machine (assuming it's a desktop OS)?

I try to execute benchmarks inside Yandex Cloud Function (analogue AWS Lambda). 

It has very limited environment, so I cannot install dotnet SDK inside it as it is too big.

Thanks!
