### ISSUE TITLE
Document how to pass value from benchmark method to column value

### ISSUE THREAD

**Issue by sandersaares** [dotnet/BenchmarkDotNet#1527] opened 2020-09-03 15:03 UTC
What I want to achieve is that a value gets from my benchmark code into the results (summary table):

```
[Benchmark()]
public void ExchangePackets()
{
    PublishColumn("Foo", "Bar");
}

|          Method | PacketCount | Foo |    Mean | Error |
|---------------- |------------ |---- |--------:|------:|
| ExchangePackets |     1000000 | Bar | 24.32 s |    NA |
```

So far I can find from the documentation how to add a new column but there's nothing on what is the right way to put values into that column from within the benchmark (I have no reference to the config or column in my benchmark method, after all). I request this gap in the documentation be addressed.

**Comment by adamsitnik** [comment] 2020-09-03 17:02
Hi @sandersaares 

This a duplicate of https://github.com/dotnet/BenchmarkDotNet/issues/784

Please see the existing issue for details and let me know if my [old proposal](https://github.com/dotnet/BenchmarkDotNet/issues/784#issuecomment-395669089) would meet your needs.

**Closed by adamsitnik** 2020-09-03 17:02 UTC
