### ISSUE TITLE
Could not install package 'BenchmarkDotNet 0.12.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6', [...]

### ISSUE THREAD

**Issue by abelbraaksma** [dotnet/BenchmarkDotNet#1334] opened 2019-12-19 12:34 UTC
_(note: this is not a report to suggest going back to supporting older versions of the .NET Framework)_

The following error is thrown when you are updating your references of BenchmarkDotNet. I found the error confusing and it took me a few minutes _and_ browsing through the "breaking changes" list until I [found this on 0.11.4](https://benchmarkdotnet.org/changelog/v0.11.4.html) to understand what was happening:

> Could not install package 'BenchmarkDotNet 0.12.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

I know now that it is caused by [this breaking change](https://github.com/dotnet/BenchmarkDotNet/pull/1032), which updates BDN to NetStandard 2.0 only. However, since this is not shown on NuGet, and the error is not immediately clear to users unfamiliar with NetStandard (and the fact that NetStandard 2.0 is only supported from .NET 4.6.1 and higher), I am putting this out here to help other users that run into the same issue.

### Workaround

* If you cannot upgrade your code to .NET 4.6.1 I think the only workaround is to stick to 0.11.3 or lower. Note that, since BDN 0.10.4 (March, 2017), the minimal requirement has been .NET 4.6, so I doubt this point-upgrade would cause a lot of problems. If you're still on .NET 4.5, you're stuck with 0.10.3 or lower.

* Otherwise, upgrade your code to .NET 4.6.1 or higher and you are good to go.

I am not aware of similar issues with .NET Core, afaik anything .NET Standard 2.0. can be used with .NET Core 2.0.

### Other comments

Note that the homepage on Github shows this info, but perhaps not on the most prominent place. In fact, I only found it there while writing this post. Perhaps that section can be moved up to right under the first paragraph and/or right under the first header?

![image](https://user-images.githubusercontent.com/16015770/71173508-32f14200-2263-11ea-8d2f-4a75910620a9.png)

Also, perhaps it adds to clarity if we include there that .NET Standard 2.0 is supported?

**Comment by abelbraaksma** [comment] 2019-12-19 14:49
As an aside, it looks like .NET 4.6.1 as a minimum may have been premature. While this is what NuGet does, [according to this list](https://github.com/dotnet/standard/blob/master/docs/versions.md), there can be numerous issues. I'm not certain whether that means consuming, or producing, but nonetheless, it is worth noting that .NET Standard 2.0 means: you should upgrade to .NET 4.7.2 or higher.

![image](https://user-images.githubusercontent.com/16015770/71182805-13fcab00-2277-11ea-833d-744122f4f61e.png)

**Comment by saneman1** [comment] 2020-01-29 17:54
Hello! I'm try to install 'BenchmarkDotNet 0.12.0' into the newly created empty project that targets  .NETFramework 4.8 and get error:
Could not install package 'BenchmarkDotNet 0.11.5'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.8', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Why???

**Comment by abelbraaksma** [comment] 2020-01-31 13:57
I don't have a definitive answer for you, but googling your error gives a few ideas:

* https://stackoverflow.com/a/46804021/111575
* https://stackoverflow.com/a/43653975/111575 

There are many more discussions related to this and I'm not enough an expert here. You may want to raise it as a separate bug if there's no trivial answer.

**Comment by saneman1** [comment] 2020-01-31 15:22
@abelbraaksma thx Abel! I am currently using the previous version of BechmarkDotNet and the relevance of this problem for me is low. I thought it would be interesting to know that the workaround "upgrade your code to .NET 4.6.1 or higher and you are good to go" don't help.

**Comment by abelbraaksma** [comment] 2020-01-31 18:43
> upgrade your code to .NET 4.6.1 or higher and you are good to go

It should work. It definitely works in the majority of cases (otherwise there would be far more reports). Likely there's another issue at hand, and we should find out what exactly.

**Comment by adamsitnik** [comment] 2020-09-11 11:19
To tell the long story short BenchmarkDotNet supports .NET Standard 2.0 because one of our main dependencies - Roslyn supports only .NET Standard 2.0 and .NET Core: https://www.nuget.org/packages/Microsoft.CodeAnalysis.CSharp/

![obraz](https://user-images.githubusercontent.com/6011991/92919505-ea9d3400-f430-11ea-9a60-70faf594122e.png)

So we don't support older versions of .NET by design and we don't plan to change that.

But there is also the other side of the .NET Standard 2.0 coin. .NET Standard 2.0 means .NET 4.6.1+. If given IDE can't install BenchmarkDotNet in .NET 4.6.1+ project it's not really our fault, it's a bug in the IDE and should be reported in the IDE issue tracker. 

@abelbraaksma thank you for creating the issue and providing workarounds. 

I am going to close the issue and mark it as "wontfix".

**Closed by adamsitnik** 2020-09-11 11:19 UTC

**Comment by abelbraaksma** [comment] 2020-09-11 19:46
Sure, totally agree, it's just out there for Google to find if people get intimate this error :).
