### ISSUE TITLE
'Fatal error. Internal CLR error.' when trying to run on .NET 8 RC1

### ISSUE THREAD

**Issue by pippinmole** [dotnet/BenchmarkDotNet#2439] opened 2023-09-27 16:23 UTC
Hey,

When running any benchmark on .NET 8, I get this error:

![image](https://github.com/dotnet/BenchmarkDotNet/assets/40035529/64222cb1-fb5e-41be-829c-da7969e4111f)

Here is the repro code:

![image](https://github.com/dotnet/BenchmarkDotNet/assets/40035529/3dce451e-b430-4434-9144-9cde3bed5e7f)

Additional information:

- Running on Windows 11 22H2
- Dotnet version: 8.0.100-rc.1.23463.5
- BenchmarkNet version: 0.13.8

**Comment by BlowaXD** [comment] 2023-10-02 07:57
Affected too

**Comment by AndreyAkinshin** [comment] 2023-10-03 15:20
@pippinmole @BlowaXD thanks for the report!
1. It seems that the problem was caused by [Rider DPA](https://www.jetbrains.com/help/rider/Dynamic_Program_Analysis.html#debugging). In order to fix the problem with .NET 8 RC1, DPA should be disabled (green triangle in the status bar). Disabled DPA is **recommended** regardless of the selected .NET SDK.
![image](https://github.com/dotnet/BenchmarkDotNet/assets/2259237/efdaa7a8-b4e6-4fa9-8747-444c5742aedb)
2. The underlying problem is specific for .NET 8 RC1 and should be fixed in .NET 8 RC2, see https://github.com/dotnet/runtime/issues/92046#issuecomment-1719432284

**Comment by AndreyAkinshin** [comment] 2023-10-03 16:56
Duplicate: https://github.com/dotnet/BenchmarkDotNet/issues/2429

**Closed by AndreyAkinshin** 2023-10-03 16:56 UTC
