### ISSUE TITLE
Add more infos to report

### ISSUE THREAD

**Issue by valentinoNguyen** [dotnet/BenchmarkDotNet#1324] opened 2019-12-08 14:51 UTC
Is there anyway in BenchmarkDotnet that I can add more information into the final report beside the params and the MEAN ?

What I want to achieve is that I want to measure also how big data that it returns from my test query beside the benchmark. 

Thank you in advance :)

**Comment by AndreyAkinshin** [comment] 2019-12-08 15:53
Hello @valentinoNguyen. Could you please provide a more specific example of what you want?

**Comment by valentinoNguyen** [comment] 2019-12-09 04:55
Hi @AndreyAkinshin , 
I have a set of benchmark testcase with the input is a SQL query statement, the test will run this query against our server then return some data.

What I have now is the benchmark result export as csv and html format. I just wonder if I can add 1 more column on the report to tell how big data is returned.

**Comment by adamsitnik** [comment] 2019-12-09 16:19
Hello @valentinoNguyen 

BenchmarkDotNet runs every benchmark in a stand-alone process. This is why if you store something in a static field etc inside the benchmark you can not access it in a custom column of the host process.

Passing all kinds of results from one process to another is non trivial, we have an ongoing discussion about how to solve this problem in https://github.com/dotnet/BenchmarkDotNet/issues/784

Possible workarounds as of today are:
* use [InProcessToolchain](https://benchmarkdotnet.org/articles/configs/toolchains.html#sample-introinprocess)
* save the data to a file in `[GlobalCleanup]` method, read it in the custom column

I am closing this issue since it's a duplicate of #784

**Closed by adamsitnik** 2019-12-09 16:19 UTC
Labels: question
