### ISSUE TITLE
JsonExporterBase doesn't include MemoryDiagnoser stats in output

### ISSUE THREAD

**Issue by codebrain** [dotnet/BenchmarkDotNet#505] opened 2017-07-26 00:50 UTC
This line never evaluates to `true`:
https://github.com/dotnet/BenchmarkDotNet/blob/master/src/BenchmarkDotNet.Core/Exporters/Json/JsonExporterBase.cs#L65

I've tried many different ways of including the MemoryDiagnoser, but with no luck.

Check out https://github.com/elastic/elasticsearch-net/tree/feature/master-profiling-benchmarking

In the end, I went with a custom JSON exporter

https://github.com/elastic/elasticsearch-net/blob/feature/master-profiling-benchmarking/src/Tests/Framework/Benchmarks/BenchmarkConfig.cs

**Comment by adamsitnik** [comment] 2017-07-26 08:34
Hi @codebrain 

This has been already fixed by @Teknikaali in #453 

The problem is that it has not has not been released yet. It's going to be a part of 0.10.9. You are [using](https://github.com/elastic/elasticsearch-net/blob/feature/master-profiling-benchmarking/src/Tests/Tests.csproj#L39) 0.10.8 which does not contain the fix.

You can either wait for 0.10.9 release (should be end of this week) or grab the preview version from our CI feed:

```xml
<packageSources>
  <add key="bdn-nightly" value="https://ci.appveyor.com/nuget/benchmarkdotnet" />
</packageSources>
```

**Closed by adamsitnik** 2017-07-26 08:34 UTC
