### ISSUE TITLE
run BenchmarkDotNet in asp.net core webapi application type

### ISSUE THREAD

**Issue by namnik** [dotnet/BenchmarkDotNet#1296] opened 2019-10-28 08:35 UTC
I saw all examples that run in console app by calling :  
<code>
BenchmarkRunner.Run<ForSpeed>();
</code>

can call this code in webapi? can call BenchmarkRunner  into asp.net core weapi application?
 **note:**
I need to benchmark my classes that have  multiple inject. 
with console app my IOC injection corrupted!

**Comment by adamsitnik** [comment] 2020-10-23 18:20
Hi @namnik 

BenchmarkDotNet was designed for very accurate micro-benchmarking. All the metrics that we report are specific to the process which is executing the benchmark. The architecture does not have a concept of multiple processes like client and server. So we can tell you have long it takes to send a web request, but we can't report how much memory the server has allocated to handle it.

Most probably https://github.com/aspnet/Benchmarks/ is what you are looking for. It has a client-server concept and can track metrics for both. And it was designed to run web server benchmarks.

Since there is nothing actionable on our side here, I am closing the issue.

Thanks,
Adam

**Closed by adamsitnik** 2020-10-23 18:20 UTC
