### ISSUE TITLE
[MemoryDiagnoser] Shows strange values for 'almost' empty benchmarks

### ISSUE THREAD

**Issue by ApmeM** [dotnet/BenchmarkDotNet#2321] opened 2023-06-07 20:54 UTC
I have created a very simple almost empty benchmark. 
Full code is here:
```
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;

[MemoryDiagnoser]
public class Program
{
    public static void Main(string[] args)
    {
        BenchmarkRunner.Run<Program>();
    }

    [Benchmark]
    public void Test()
    {
        for (var i = 0; i < 10000000; i++)
        {
        }
    }
}
```

So effectively there is only a single loop from 1 to 10000000 without any calculations in it.

The benchmark result shows this:

BenchmarkDotNet=v0.13.1, OS=debian 11
Intel Core i7-8650U CPU 1.90GHz (Kaby Lake R), 1 CPU, 8 logical and 4 physical cores
.NET SDK=7.0.203
  [Host]     : .NET 6.0.10 (6.0.1022.47605), X64 RyuJIT
  DefaultJob : .NET 6.0.10 (6.0.1022.47605), X64 RyuJIT

| Method |     Mean |     Error |    StdDev | Allocated |
|------- |---------:|----------:|----------:|----------:|
|   Test | 2.605 ms | 0.0169 ms | 0.0141 ms |       3 B |

Where those 3 bytes come from? 
I run this code with this command:
```
dotnet run -c Release
```

**Comment by timcassell** [comment] 2023-06-07 21:54
See #1543

**Comment by ApmeM** [comment] 2023-06-08 05:53
Ok, thanks, it looks related, so closing this bug as duplicate.

**Comment by adamsitnik** [comment] 2023-06-08 10:54
Closing as a duplicate of #1542, @ApmeM as a workaround you can disable the Tiered JIT via env var.

**Closed by adamsitnik** 2023-06-08 10:54 UTC
