### ISSUE TITLE
Benchmark run hangs (cross posted)

### ISSUE THREAD

**Issue by haf** [dotnet/BenchmarkDotNet#755] opened 2018-05-14 13:11 UTC
For this file, for this commit: https://github.com/logary/logary/pull/323/commits/ea92a3100448ab0f08d38ad5de648037bb0e79d0#diff-cbbb0385061843b23b3a711c7714277c

Running it from `Logary/src/Logary.PerfTests` and branch `(feature/benchmarks)`

    $ dotnet run --framework netcoreapp2.0 --configuration Release
   
hangs like this:
```
// all four benchmarks run successfully here...

// AfterAll

Mean = 759.6803 us, StdErr = 3.8824 us (0.51%); N = 25, StdDev = 19.4120 us
Min = 730.1411 us, Q1 = 747.7047 us, Median = 754.4475 us, Q3 = 770.6627 us, Max = 806.2296 us
IQR = 22.9580 us, LowerFence = 713.2678 us, UpperFence = 805.0996 us
ConfidenceInterval = [745.1392 us; 774.2214 us] (CI 99.9%), Margin = 14.5411 us (1.91% of Mean)
Skewness = 0.62, Kurtosis = 2.76, MValue = 2

// ***** BenchmarkRunner: Finish  *****

// * Export *
  BenchmarkDotNet.Artifacts\results\BP-report.csv
  BenchmarkDotNet.Artifacts\results\BP-report.html
  BenchmarkDotNet.Artifacts\results\BP-measurements.csv
  BuildPlots.R
// hangs here
```

```fsharp

module Tests =
  open BenchmarkDotNet.Diagnosers
  open BenchmarkDotNet.Exporters.Csv
  open BenchmarkDotNet.Reports

  // http://adamsitnik.com/the-new-Memory-Diagnoser/
  // https://benchmarkdotnet.org/Advanced/Params.htm
  // https://github.com/logary/logary/pull/323/files
  [<Tests>]
  let benchmarks =
    let config xJ =
      { benchmarkConfig with
          exporters =
            [ new CsvExporter(CsvSeparator.Comma)
              new Exporters.HtmlExporter()
              new Exporters.RPlotExporter()
            ]
          diagnosers =
            [ new MemoryDiagnoser() ]
          jobs = [ xJ ]
      }

    testList "benchmarks" [
      test "backpressure" {
        let cfg = config (Job(Job.Core, baseJob))
        let summary: Summary = benchmark<BP> cfg (id >> box) |> unbox
        ()
      }

      test "simple" {
        let cfg = config (Job(Job.Core, baseJob))
        let summary: Summary = benchmark<Simple> cfg (id >> box) |> unbox
        ()
      }

      test "ack" {
        let cfg = config (Job(Job.Core, baseJob))
        let summary: Summary = benchmark<ACK> cfg (id >> box) |> unbox
        ()
      }
    ]
```

**Comment by adamsitnik** [comment] 2018-05-27 20:06
Hello @haf 

This issue is a duplicate of #641, I faced the same problem, [here](https://github.com/dotnet/BenchmarkDotNet/issues/641#issuecomment-367713275) you can find the explanation (TLDR: when you use this exporter for the first time, R is downloading all the required packages and it takes a LOT of time)

**Closed by adamsitnik** 2018-05-27 20:06 UTC
