### ISSUE TITLE
Two consecutive BenchmarkRunner.Run commands fail

### ISSUE THREAD

**Issue by jzabroski** [dotnet/BenchmarkDotNet#1092] opened 2019-03-06 19:57 UTC
```csharp
using BenchmarkDotNet.Running;

namespace JohnZabroski.Performance.Runner
{
    class Program
    {
        static void Main(string[] args)
        {
            BenchmarkRunner.Run<DataBucketingRandomPeriodsPerformanceTest>();
            BenchmarkRunner.Run<DataBucketingSequentialPeriodsPerformanceTest>(); // fails
        }
    }
}
```

Message & Stack trace:

```
System.Runtime.InteropServices.COMException: 'The WMI data block or event notification has already been enabled. (Exception from HRESULT: 0x8007106E)'

   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.Diagnostics.Tracing.Session.TraceEventProfileSources.Set(Int32[] profileSourceIDs, Int32[] profileSourceIntervals)
   at BenchmarkDotNet.Diagnostics.Windows.PmcDiagnoser.GetInitializedStats(DiagnoserActionParameters parameters)
   at BenchmarkDotNet.Diagnostics.Windows.EtwDiagnoser`1.Start(DiagnoserActionParameters parameters)
   at BenchmarkDotNet.Diagnosers.CompositeDiagnoser.Handle(HostSignal signal, DiagnoserActionParameters parameters)
   at BenchmarkDotNet.Loggers.SynchronousProcessOutputLoggerWithDiagnoser.ProcessInput()
   at BenchmarkDotNet.Toolchains.DotNetCli.DotNetCliExecutor.Execute(BenchmarkCase benchmarkCase, BenchmarkId benchmarkId, ILogger logger, ArtifactsPaths artifactsPaths, IDiagnoser diagnoser, String executableName, IResolver resolver)
   at BenchmarkDotNet.Toolchains.DotNetCli.DotNetCliExecutor.Execute(ExecuteParameters executeParameters)
   at BenchmarkDotNet.Running.BenchmarkRunnerClean.RunExecute(ILogger logger, BenchmarkCase benchmarkCase, BenchmarkId benchmarkId, IToolchain toolchain, BuildResult buildResult, IResolver resolver, IDiagnoser diagnoser, Boolean& success)
   at BenchmarkDotNet.Running.BenchmarkRunnerClean.Execute(ILogger logger, BenchmarkCase benchmarkCase, BenchmarkId benchmarkId, IToolchain toolchain, BuildResult buildResult, IResolver resolver)
   at BenchmarkDotNet.Running.BenchmarkRunnerClean.RunCore(BenchmarkCase benchmarkCase, BenchmarkId benchmarkId, ILogger logger, IResolver resolver, BuildResult buildResult)
   at BenchmarkDotNet.Running.BenchmarkRunnerClean.Run(BenchmarkRunInfo benchmarkRunInfo, Dictionary`2 buildResults, IResolver resolver, ILogger logger, List`1 artifactsToCleanup, String rootArtifactsFolderPath, StartedClock& runChronometer)
   at BenchmarkDotNet.Running.BenchmarkRunnerClean.Run(BenchmarkRunInfo[] benchmarkRunInfos)
   at BenchmarkDotNet.Running.BenchmarkRunner.RunWithDirtyAssemblyResolveHelper(Type type, IConfig config)
   at BenchmarkDotNet.Running.BenchmarkRunner.Run[T](IConfig config)
   at JohnZabroski.Performance.Runner.Program.Main(String[] args) in D:\Source\JohnZabroski.Performance.Runner\Program.cs:line 13
```

**Comment by wojtpl2** [comment] 2019-03-19 09:05
@jzabroski I had the same exception. Could you try to restart your computer and then run this test again. In my situation, it helped. 

This exception can be reproduced by stopping benchmark with e.g. `Add(HardwareCounter.CacheMisses);` and then during every next run, you will get this exception. 

@jzabroski Could you share source code of `DataBucketingRandomPeriodsPerformanceTest` and `DataBucketingSequentialPeriodsPerformanceTest`? If you can not share the whole source code, please share the configuration of these tests.

**Comment by jzabroski** [comment] 2019-03-19 14:29
@wojtpl2 dzień dobry!

> This exception can be reproduced by stopping benchmark with e.g. `Add(HardwareCounter.CacheMisses);` and then during every next run, you will get this exception.

Hmm! That sounds about right.  I suspected the issue only triggers due to the fact I am using the "third party" Event Tracing for Windows library/dependency, but didn't have time to investigate why.  I'll try to wire up an example next week.  I don't think the test itself matters - it just needs to be long enough to hit Control+C in the terminal to kill the console.  You can literally benchmark `Task.Delay(5000)` and interrupt that.

**Comment by adamsitnik** [comment] 2019-03-19 14:47
@jzabroski jaki ten świat jest mały ;)

did you try 0.11.4? I am asking because I thought I have solved this issue in https://github.com/dotnet/BenchmarkDotNet/pull/1061

**Comment by jzabroski** [comment] 2019-03-19 19:54
@adamsitnik ostatnia imprezza - here we go!

https://github.com/dotnet/BenchmarkDotNet/blob/cf3f8c382a6aab8fbc5c7ce804ef7451a4fdfac7/src/BenchmarkDotNet.Diagnostics.Windows/EtwDiagnoser.cs#L93

This looks incorrect.  Or rather, the whole "WaitForDelayedEvents" thing is a bit hacky - most code paths except for rude aborts call this method to clean-up.   I'm not sure what the proper fix is here.  Through the magic of GitHub, I found this snippet with illuminating comments: https://github.com/Microsoft/dotnet-samples/blob/master/Microsoft.Diagnostics.Tracing/TraceEvent/TraceEvent/10_SimpleEventSourceMonitor.cs#L74-L95 - I think this is the right way to clean it up.  I think, in the event that CreateSession takes a long time (as in 1 ns), you will end up in a situation where you have created the session but not hooked the handler.  I think you need to flip the order of wiring the event handler and creating the session.  This will guarantee the cancel hook is called and the session is disposed.   Do you agree?

**Comment by adamsitnik** [comment] 2019-03-20 18:01
> This looks incorrect

```cs
 private void OnConsoleCancelKeyPress(object sender, ConsoleCancelEventArgs e) => Session?.Dispose(); 
```

Why? The code that you have referenced does exactly the same thing (without null check)

https://github.com/Microsoft/dotnet-samples/blob/6f2414148e33740c29116138e8bcef28364fafa8/Microsoft.Diagnostics.Tracing/TraceEvent/TraceEvent/10_SimpleEventSourceMonitor.cs#L95

```cs
Console.CancelKeyPress += delegate(object sender, ConsoleCancelEventArgs e) { session.Dispose(); };
```

> the whole "WaitForDelayedEvents" thing is a bit hack

I agree, but we do that only because we have to. Some ETW events might be delayed and we wait for them.

This particular error is related to Hardware Counters, which is a very rarely used ETW feature. I think that this issue requires some deep investigation. Maybe `session.Dispose` is simply not enough?

**Comment by jzabroski** [comment] 2019-03-20 18:10
Sorry, I was not clear - that is my fault. Hope you can forgive me.  My proposal is that you do this:

```csharp
        protected void Start(DiagnoserActionParameters parameters)
        {
            Clear();

            BenchmarkToProcess.Add(parameters.BenchmarkCase, parameters.Process.Id);
            StatsPerProcess.TryAdd(parameters.Process.Id, GetInitializedStats(parameters));
            // important! Wire up event handlers for disposing session before acquiring the session, to avoid situations where the user hits Control+C between CreateSession and delegate combine
            Console.CancelKeyPress += OnConsoleCancelKeyPress;
            AppDomain.CurrentDomain.ProcessExit += OnProcessExit;

            Session = CreateSession(parameters.BenchmarkCase);
```

In other words, I think your code should work in 99.99999% of situations.  But it's definitely possible you won't dispose of the session.  The simplest way I can think of to test this would be to call System.Environment.Exit(-666) right after create session to see my point.

**Comment by jzabroski** [comment] 2019-03-20 18:20
Separately, how does calling .Run clean up an ETW session?

> did you try 0.11.4? I am asking because I thought I have solved this issue in #1061

Confirmed repro in 0.11.4, here is my csproj:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.11.4" />
    <PackageReference Include="BenchmarkDotNet.Diagnostics.Windows" Version="0.11.4" />
    <PackageReference Include="Microsoft.Diagnostics.Tracing.TraceEvent" Version="2.0.38" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Weiss.Ecesis.Services.Tests\Weiss.Ecesis.Services.Tests.csproj" />
  </ItemGroup>

</Project>
```

**Comment by adamsitnik** [comment] 2019-03-20 18:31
@jzabroski Now I understand. And I agree, that this case is not handled. We should most probably handle it when starting the sesssion (kill the previous one if it somehow survived)

**Comment by jzabroski** [comment] 2019-03-20 18:34
In thinking about my peer review of your code fix further, I think the example I linked to as best practice is also incorrect and suffers the same fate.  They should similarly register the delegate prior to the using statement, because a finally clause is not guaranteed to execute if, say, another thread triggers `System.Environment.Exit(-666);` https://docs.microsoft.com/en-us/dotnet/api/system.environment.exit?view=netframework-4.7.2

**Comment by jzabroski** [comment] 2019-03-20 18:37
> @jzabroski Now I understand. And I agree, that this case is not handled. We should most probably handle it when starting the session (kill the previous one if it somehow survived)

I was going to suggest something similar but I would like to avoid such complicated semantics if we can.  I think the broader issue is with BenchmarkRunner.Run and how it manages the resources it acquires (e.g., TraceEventSession).  I'm still learning BenchmarkDotNet so I haven't had enough time to F10 through the whole project and understand how everything hangs together.

**Comment by jzabroski** [comment] 2019-03-20 18:45
> In thinking about my peer review of your code fix further, I think the example I linked to as best practice is also incorrect and suffers the same fate. They should similarly register the delegate prior to the using statement, because a finally clause is not guaranteed to execute if, say, another thread triggers `System.Environment.Exit(-666);` https://docs.microsoft.com/en-us/dotnet/api/system.environment.exit?view=netframework-4.7.2

I created an issue for the code sample: https://github.com/Microsoft/dotnet-samples/issues/44

**Comment by jzabroski** [comment] 2019-03-22 17:41
@wojtpl2 @adamsitnik I had another idea (in addition to the fix I propose with the non-obvious sequencing the delegate registration before resource acquisition).  The idea also comes from the dotnet-samples repository comments:

https://github.com/Microsoft/dotnet-samples/blob/6f2414148e33740c29116138e8bcef28364fafa8/Microsoft.Diagnostics.Tracing/TraceEvent/TraceEvent/10_SimpleEventSourceMonitor.cs#L72-73

> ```csharp
>          Out.WriteLine("Use 'logman query -ets' to see active sessions.");
>          Out.WriteLine("Use 'logman stop {0} -ets' to manually stop orphans.", sessionName);
> ```

I guess, the question becomes how to create a unique sessionName that also thumbprints when the session was created, such that there is actually a clean way to clean up orphaned sessions.  I believe BenchmarkDotNet currently uses Guid generation for the name.  It might make more sense to do a timestamp prefix plus a guid.

**Comment by adamsitnik** [comment] 2020-10-23 21:01
With the next version of BenchmarkDotNet, we are going to discontinue the mentioned `PmcDiagnoser` in favor of a much more accurate `EtwProfiler` diagnoser which is also capable of getting hardware information: #1548

Moreover, we are internally going to enable it on the .NET Team for the regular runs of thousands of benchmarks that we have in the performance repo. So if there will be any reliability issue like the one mentioned here, it will definitely pop up very quickly. And we will be a force to fix it.

Having said that, I am going to close the issue now.

**Closed by adamsitnik** 2020-10-23 21:01 UTC

**Comment by jzabroski** [comment] 2020-10-23 21:04
Ok. But in terms of moving away from Guids to a timestamps based approach, Twitter's Snowflake ID generator comes to mind
