### ISSUE TITLE
How to pass parameters to whole benchmark suite

### ISSUE THREAD

**Issue by dbogatov** [dotnet/BenchmarkDotNet#808] opened 2018-06-28 02:29 UTC
Hi everyone,

Forgive me if the answer is in docs, I just have not found it.

How do I pass a parameter to the whole benchmark suite?
`Param` and `Argument` are not what I want.

For example, say I have a function that operates on a list of numbers.
One benchmark is performing an operation on the whole list.
However, I want to control the size of that list.
I want to be able to set it small or large.

Here is it, I do not want to run benchmark for both, I want to run for one.
Can I say `.Run(new[] { $"--namespace=Benchmark.{@namespace}", "--join", "--my-param={value}" });` ?

Reason for me is to be able to run this in CI, where I would supply little values to just make sure routine works.
Something like `dotnet run -c RELEASE -- --scale 0.001`.

**Comment by dbogatov** [comment] 2018-06-28 02:43
Somewhat related.
Can I manually run `ExecutionValidator`?

**Comment by adamsitnik** [comment] 2018-06-28 10:50
Hi @dbogatov 

It's not a supported scenario.

> Reason for me is to be able to run this in CI, where I would supply little values to just make sure routine works.

Then you can use `Job.Dry` which tells BenchmarkDotNet to run the benchmarks just once. It should be a fast validation that benchmarks are OK

> Can I manually run ExecutionValidator?

You can take a look at [ExecutionValidatorTest](https://github.com/dotnet/BenchmarkDotNet/blob/7b47c66f25786298179929c1205646bcdc1e838a/tests/BenchmarkDotNet.Tests/Validators/ExecutionValidatorTests.cs) for some ideas.

**Comment by dbogatov** [comment] 2018-06-28 21:46
Dry job method actually works well for me.

**Comment by adamsitnik** [comment] 2018-06-28 22:03
@dbogatov could you try to define the arguments as ulongs in explicit way?

```cs
[Arguments(0ul, 1ul)]
[Arguments(5ul, 55ul)]
[Arguments(5ul, 555ul)]
[Arguments(5ul, 55555ul)]
[Arguments(0ul, ulong.MaxValue)]
```

**Comment by dbogatov** [comment] 2018-06-28 22:06
Did it, same result.

**Comment by adamsitnik** [comment] 2019-01-30 02:58
The original question was answered, I am not able to reproduce the mentioned problem so I am closing the issue.

**Closed by adamsitnik** 2019-01-30 02:58 UTC
Labels: question
