### ISSUE TITLE
async GlobalSetup broken when debugging

### ISSUE THREAD

**Issue by crone66** [dotnet/BenchmarkDotNet#2649] opened 2024-09-25 13:13 UTC
I came across a really strange behavior. If I debug the following code, the field "set" will never be set to true because as soon as I hit the await keyword the setup will be aborted and jump right into the benchmark. In the benchmark I could verify that the field was indeed not set to true by debugger and if statement. I used the DebugInProcessConfig and Visual Studio 2022. Without debugger everything works as expected. 

As workaround I replaced await with `.GetAwaiter().GetResult()` which worked as expected.

```c#
privat bool set;

[GlobalSetup]
public async Task Setup()
{
    await Task.Delay(500);
    set = true; //will never be set in debug mode
}

[Benchmark]
public void Test()
{
    if(!set)
        throw new Exception("not set"); //triggered only while debugging
}
```

**Comment by timcassell** [comment] 2024-09-25 13:31
Duplicate of #1738

**Closed by timcassell** 2024-09-25 13:31 UTC
