### ISSUE TITLE
Benchmark returning ValueTask can fail in .NET 5.0 while work in .NET Core 3.1

### ISSUE THREAD

**Issue by Turnerj** [dotnet/BenchmarkDotNet#1650] opened 2021-02-09 14:24 UTC
This is a bit of a weird one and may more highlight a bad use of `ValueTask` in my own code than anything else but thought I'd still raise this here as I'm not 100% sure.

Take this minimum example I've managed to extrapolate from my original code:
```csharp
[SimpleJob(RuntimeMoniker.NetCoreApp50)]
public class BDNErrorBenchmark
{
	[Benchmark]
	public async ValueTask ThisWorks()
	{
		await (new ValueTask<int>(50));
	}

	[Benchmark]
	public async ValueTask ThisDoesnt()
	{
		await Task.Delay(10);
	}
}
```

The benchmark `ThisWorks` works in .NET 5.0 and .NET Core 3.1 whereas `ThisDoesnt` fails in .NET 5.0 BUT works in .NET Core 3.1. When it fails, I get the following exception after overhead jitting:

> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at BenchmarkDotNet.Autogenerated.Runnable_1.<.ctor>b__3_4() in C:\Users\James\source\repos\TurnerSoftware\CacheTower\benchmarks\CacheTower.Benchmarks\bin\Release\net5.0\52cfda19-4122-4d5a-bddd-cee87aa8a8a9\52cfda19-4122-4d5a-bddd-cee87aa8a8a9.notcs:line 917
   at BenchmarkDotNet.Autogenerated.Runnable_1.WorkloadActionNoUnroll(Int64 invokeCount) in C:\Users\James\source\repos\TurnerSoftware\CacheTower\benchmarks\CacheTower.Benchmarks\bin\Release\net5.0\52cfda19-4122-4d5a-bddd-cee87aa8a8a9\52cfda19-4122-4d5a-bddd-cee87aa8a8a9.notcs:line 1570
   at BenchmarkDotNet.Engines.Engine.RunIteration(IterationData data)
   at BenchmarkDotNet.Engines.EngineFactory.Jit(Engine engine, Int32 jitIndex, Int32 invokeCount, Int32 unrollFactor)
   at BenchmarkDotNet.Engines.EngineFactory.CreateReadyToRun(EngineParameters engineParameters)
   at BenchmarkDotNet.Autogenerated.Runnable_1.Run(IHost host, String benchmarkName) in C:\Users\James\source\repos\TurnerSoftware\CacheTower\benchmarks\CacheTower.Benchmarks\bin\Release\net5.0\52cfda19-4122-4d5a-bddd-cee87aa8a8a9\52cfda19-4122-4d5a-bddd-cee87aa8a8a9.notcs:line 896
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at BenchmarkDotNet.Autogenerated.UniqueProgramName.AfterAssemblyLoadingAttached(String[] args) in C:\Users\James\source\repos\TurnerSoftware\CacheTower\benchmarks\CacheTower.Benchmarks\bin\Release\net5.0\52cfda19-4122-4d5a-bddd-cee87aa8a8a9\52cfda19-4122-4d5a-bddd-cee87aa8a8a9.notcs:line 48

The line of code it refers to near the top of the stack looks like this in the "notcs" file:
```csharp
        public Runnable_1()
        {
            globalSetupAction = () => { };
            globalCleanupAction = () => { };
            iterationSetupAction = () => { };
            iterationCleanupAction = () => { };
            overheadDelegate = __Overhead;
            workloadDelegate = () => { ThisDoesnt().GetAwaiter().GetResult(); }; // <- This line
            
        }
```

I can recreate this error outside of BDN if I specifically use `.GetAwaiter().GetResult()` but not when I use `await`. I tried to see if the "notcs" file was different for the .NET 5 benchmark vs the .NET Core 3.1 but they looked identical. I feel that it would indicate the issue might actually be the runtime but I don't know for certain.

I did find that switching from a `ValueTask` return type to `Task` for the methods that throw the exception during benchmarking works but I'm not sure if that means this is a legit bug or I'm just using `ValueTask` wrong. The actual benchmark where I discovered this [is here](https://github.com/TurnerSoftware/CacheTower/blob/936cc00a4f5ff05da53fcb148f1c9e89667acb66/benchmarks/CacheTower.Benchmarks/Providers/CacheLayerComparisonBenchmark.cs) where my `MemoryCacheLayer` succeeds but all my other cache layers fail with that same error.

Either way, thought I'd raise it to get your input.

**Comment by Turnerj** [comment] 2021-02-09 14:25
It _may_ relate to #1595 but I'm not 100% sure.

**Comment by timcassell** [comment] 2021-02-15 04:16
> I can recreate this error outside of BDN if I specifically use `.GetAwaiter().GetResult()` but not when I use `await`. I tried to see if the "notcs" file was different for the .NET 5 benchmark vs the .NET Core 3.1 but they looked identical. I feel that it would indicate the issue might actually be the runtime but I don't know for certain.

That definitely sounds like a runtime bug. You should report that in https://github.com/dotnet/runtime/issues

**Comment by adamsitnik** [comment] 2021-02-15 10:40
It's a duplicate of #1595, please follow it for the updates (I don't plan to fix it in the near future as I am simply too busy with other things)

**Closed by adamsitnik** 2021-02-15 10:40 UTC

**Comment by Turnerj** [comment] 2021-02-15 12:09
> It's a duplicate of #1595, please follow it for the updates (I don't plan to fix it in the near future as I am simply too busy with other things)

Thanks for confirming! No sweat for fixing it - I'm sure we're all juggling a bunch of things! Plus it looks like @timcassell might be making some progress via #1595. The specifics for the interaction for tasks and awaiting isn't something I've dug into a large amount so it is all a bit over my head so there isn't really any additional help I think I can provide.

Anyway, hope you smash your work or other things you're busy doing! 🙂
