### ISSUE TITLE
ParamsSource with a null value InvalidOperationException

### ISSUE THREAD

**Issue by liebasam** [dotnet/BenchmarkDotNet#2010] opened 2022-05-19 15:40 UTC
Using a value of `null` in a ParamsSource causes an exception before any benchmarks are run. Surprised I'm the first one to run into this!

Code sample that reproduces the issue.
```
class SomeBench {
public static IEnumerable<object> AllObjectsToTest { get; } = new object[] { null };

[ParamsSource(nameof(AllObjectsToTest))]
public static object ObjectToTest { get; set; }

[Benchmark]
public void MyBenchmark() => Console.WriteLine(ObjectToTest);

public static void Main(string[] args)
{
  BenchmarkSwitcher.FromAssembly(typeof(SomeBench).Assembly).Run(args);
  return 0;
}
}
```

Exception seen from the command line.
```
Unhandled exception. System.InvalidOperationException: Failed to compare two elements in the array.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at BenchmarkDotNet.Parameters.SmartParameter.get_DisplayText()
   at BenchmarkDotNet.Parameters.ParameterInstance.ToDisplayText(CultureInfo cultureInfo, Int32 maxParameterColumnWidth)
   at BenchmarkDotNet.Parameters.ParameterInstance.ToDisplayText()
   at BenchmarkDotNet.Parameters.ParameterInstances.<>c.<get_DisplayInfo>b__15_0(ParameterInstance p)
   at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()
   at System.String.Join(String separator, IEnumerable`1 values)
   at BenchmarkDotNet.Parameters.ParameterInstances.get_DisplayInfo()
   at BenchmarkDotNet.Running.BenchmarkCase.get_DisplayInfo()
   at BenchmarkDotNet.Order.DefaultOrderer.BenchmarkComparer.Compare(BenchmarkCase x, BenchmarkCase y)
   at System.Collections.Generic.ArraySortHelper`1.InsertionSort(Span`1 keys, Comparison`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntroSort(Span`1 keys, Int32 depthLimit, Comparison`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntrospectiveSort(Span`1 keys, Comparison`1 comparer)
   at System.Collections.Generic.GenericArraySortHelper`1.Sort(Span`1 keys, IComparer`1 comparer)
```

**Comment by mawosoft** [comment] 2022-05-19 16:25
Dupe of #1809, fixed in #1810. 

Will be part of the next official release. In the meantime, you can use the [nightly builds](https://benchmarkdotnet.org/articles/guides/nuget.html). 

Just be careful to pick a version that has been actually build from the master branch. There are still some problems with the AppVeyor feed (See #1937).

**Closed** 2022-05-19 16:54 UTC
