### ISSUE TITLE
Adding custom data to system info

### ISSUE THREAD

**Issue by surban** [dotnet/BenchmarkDotNet#732] opened 2018-04-27 08:23 UTC
At the top of each benchmark result, BenchmarkDotNet produces a system info block that looks like this.

```
BenchmarkDotNet=v0.10.14, OS=Windows 10.0.17134
Intel Xeon CPU E5-1650 v2 3.50GHz, 1 CPU, 12 logical and 6 physical cores
.NET Core SDK=2.1.300-preview2-008533
  [Host]   : .NET Core 2.1.0-preview2-26406-04 (CoreCLR 4.6.26406.07, CoreFX 4.6.26406.04), 64bit RyuJIT
  ShortRun : .NET Core 2.1.0-preview2-26406-04 (CoreCLR 4.6.26406.07, CoreFX 4.6.26406.04), 64bit RyuJIT

Job=ShortRun  LaunchCount=1  TargetCount=3  
WarmupCount=3  
```

I would like to add custom information to this block for my benchmarks, for example the name of the GPU in the system or some configuration details of the software I am benchmarking.

This is probably already possible with the available API, but I was not able to figure out how to do it. Could you point me into the right direction?

**Comment by AndreyAkinshin** [comment] 2018-04-27 17:48
Hey @surban, thanks for the feature request. It's a duplicate of https://github.com/dotnet/BenchmarkDotNet/issues/384. I completely forgot about this issue, so it's not supported yet. I will try to find some time and implement it in `v0.11.0`. Please, track #384 for updates.

**Closed by AndreyAkinshin** 2018-04-27 17:48 UTC
