### ISSUE TITLE
Run benchmarks without source code and with multiple RuntimeMonikers

### ISSUE THREAD

**Issue by djfoxer** [dotnet/BenchmarkDotNet#1721] opened 2021-06-06 19:49 UTC
Hi. Is it possible to run benchmark app without source code for multiple runtimes SDK?

I created class with multiple RuntimeMonikers by using SimpleJob attribute (Net48,NetCoreApp31,Net50). When I run my app without source code I get error "BenchmarkDotNet has failed to build the auto-generated boilerplate code.". Ofcourse I can add [InProcess] attribute but it only allows to run benchmark for SDK that exe file was builded (in my case exe file was builded in .NET 5).

Currently I can solve my issue only by building multiple exe files using selected SDK (Net48,NetCoreApp 31,Net50). Could I (somehow) build one exe (without source code) that can test multiple SDK (multiple RuntimeMonikers)? 

Btw, Thank you for your great work!

**Comment by adamsitnik** [comment] 2021-06-07 06:33
Hi @djfoxer 

> Is it possible to run benchmark app without source code for multiple runtimes SDK?

It is not. BenchmarkDotNet generates boilerplate code and we simply have to compile it. As you have noticed `InProcessToolchain` does not have this requirement, but you need to compile the exes on your own.

Since this is by design and we don't plan to change it, I am going to close the issue.

**Closed by adamsitnik** 2021-06-07 06:33 UTC
