### ISSUE TITLE
Plots of benchmarks without params have a double dash (--) in the name

### ISSUE THREAD

**Issue by simonech** [dotnet/BenchmarkDotNet#1183] opened 2019-06-24 17:51 UTC
For each Job, it adds plots about density, cumulative mean, and so on. But two files are named `BenchmarkDotNet.Artifacts/results/MyBench.Sleeps-Time50--density.png` and `BenchmarkDotNet.Artifacts/results/MyBench.Sleeps-Time50--facetDensity.png`, with the `--` instead of single. Like some iteration variable is empty (since later there are names with `-Default-`
![image](https://user-images.githubusercontent.com/61557/59975824-efbc5c00-95bc-11e9-8576-a09b832c2c64.png)

I've noticed that this last error only happens without parameters. When there are parameters involved, there are no `--`  files.

**Comment by marcnet80** [comment] 2019-07-22 12:21
Hi, @AndreyAkinshin. Is this issue still actual? I can't reproduce it on Windows 10, R-3.6.1.
`   internal string GetArtifactFullName(Summary summary)
        {
            string fileName = GetFileName(summary);
            return $"{Path.Combine(summary.ResultsDirectoryPath, fileName)}-{FileCaption}{FileNameSuffix}.{FileExtension}";
        }`

**Comment by AndreyAkinshin** [comment] 2019-07-22 15:03
@marcnet80 yes, the issue is still actual. I guess, the problem is in this line: https://github.com/dotnet/BenchmarkDotNet/blob/v0.11.5/src/BenchmarkDotNet/Templates/BuildPlots.R#L112
When `params` is empty, we get double dash in the file name.

**Comment by marcnet80** [comment] 2019-07-23 08:10
@AndreyAkinshin, thank you for pointing, values for params are coming from generated  ..-measurements.csv in this line of code: 
https://github.com/dotnet/BenchmarkDotNet/blob/v0.11.5/src/BenchmarkDotNet/Templates/BuildPlots.R#L104
I open ..-measurements.csv and see that values for **Params** columns is empty, that's why @simonech  has `--` 
![image](https://user-images.githubusercontent.com/46241368/61690884-00cec900-ad33-11e9-873d-973276d4fc73.png)
I can fix it in R-script, by checking params and adding additional variable or maybe better add default value for Params column in C#: 
https://github.com/dotnet/BenchmarkDotNet/blob/v0.11.5/src/BenchmarkDotNet/Exporters/Csv/CsvMeasurementsExporter.cs#L98
Something like this (of course wrapp it in Presenter):
`columns.Add(new MeasurementColumn("Params", (summary, report, m) => string.IsNullOrEmpty(report.BenchmarkCase.Parameters.PrintInfo) ? "Default" : report.BenchmarkCase.Parameters.PrintInfo));`

**Comment by AndreyAkinshin** [comment] 2019-07-24 09:28
@marcnet80 it's better to fix it in the R-script.

**Comment by marcnet80** [comment] 2019-07-24 21:10
Ok. Pull-request added.

**Comment by adamsitnik** [comment] 2020-10-23 19:39
Fixed long time ago in #1212, I am closing the issue

**Closed by adamsitnik** 2020-10-23 19:39 UTC
Labels: good first issue, help wanted, up-for-grabs
