### ISSUE TITLE
NullReferenceException in v0.12.1

### ISSUE THREAD

**Issue by sdanyliv** [dotnet/BenchmarkDotNet#1620] opened 2020-12-16 14:14 UTC
Hi, 
I don't think I can create small reproducible sample but probably this call stack should help.
```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at BenchmarkDotNet.Analysers.MultimodalDistributionAnalyzer.AnalyseReport(BenchmarkReport report, Summary summary)+MoveNext()
   at BenchmarkDotNet.Analysers.AnalyserBase.Analyse(Summary summary)+MoveNext()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Set`1.UnionWith(IEnumerable`1 other)
   at System.Linq.Enumerable.DistinctIterator`1.FillSet()
   at System.Linq.Enumerable.DistinctIterator`1.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at BenchmarkDotNet.Running.BenchmarkRunnerClean.PrintSummary(ILogger logger, ImmutableConfig config, Summary summary)
   at BenchmarkDotNet.Running.BenchmarkRunnerClean.Run(BenchmarkRunInfo[] benchmarkRunInfos)
   at BenchmarkDotNet.Running.BenchmarkSwitcher.RunWithDirtyAssemblyResolveHelper(String[] args, IConfig config)
   at BenchmarkDotNet.Running.BenchmarkSwitcher.Run(String[] args, IConfig config)
```

**Comment by adamsitnik** [comment] 2020-12-18 07:38
Hi @sdanyliv 

It's a duplicate of #1448 which has been already solved in #1488 but just not yet released to nuget.org

To avoid this problem you can either update to the latest preview version: https://benchmarkdotnet.org/articles/guides/nuget.html#nightly

Or wait until we publish a new version to NuGet.org

Thanks

**Closed by adamsitnik** 2020-12-18 07:38 UTC
