### ISSUE TITLE
Compare benchmarks across supported platforms

### ISSUE THREAD

**Issue by glen-nicol** [dotnet/BenchmarkDotNet#1868] opened 2021-12-10 19:18 UTC
Hi there, thanks for the great tool. I am trying to benchmark improvements made moving to newer API's that are not available in .Net 4.8. In my case ReadonlySpan<T> (because my library targets NetStandard 2.0, but it is available in 2.1 which .Net 4.8 does not support).

Currently I have a benchmark class setup such that the benchmark function calling the span function is just empty in the .Net 4.8 because the benchmark engine throws errors if I remove the function entirely with a preprocessor. 

Is there a better way? I imagine the function not existing overlaps with other error cases. Could an attribute be added to remove a benchmark based on the runtime? If there already is I apologize I looked through them and saw OS filters but not runtime filters that weren't deprecated (CoreJob, MonoJob and I saw those were meant for something else).

**Comment by mawosoft** [comment] 2021-12-10 20:00
There isn't a better way. This came up recently here (#1863). And here ( [#1226 (comment)](https://github.com/dotnet/BenchmarkDotNet/issues/1226#issuecomment-532144829)) Adam Sitnik explains why it is by design.

**Comment by glen-nicol** [comment] 2021-12-10 23:32
K, I understand the need to make the API from the host process consistent. But what about the idea to use attributes to filter out by runtime to suppress that warning and avoid running a throwaway benchmark.

**Comment by adamsitnik** [comment] 2021-12-16 09:16
@glen-nicol as @mawosoft wrote, this is by design: https://github.com/dotnet/BenchmarkDotNet/issues/1226#issuecomment-532144829 :

> This is by design.

> When running the host process targetting XYZ framework, BDN is using the reflection to obtain the list of available methods (benchmarks). If you are using `#if` defines, then the list of benchmarks is going to be different per host process target framework.

> Performance repo docs describe how to compare multiple runtimes performance here:
https://github.com/dotnet/performance/blob/master/docs/benchmarkdotnet.md#multiple-runtimes

> The host process needs to be the lowest common API denominator of the runtimes you want to compare!

But getting back to your question:

> But what about the idea to use attributes to filter out by runtime to suppress that warning and avoid running a throwaway benchmark

BDN already supports filtering and you can create such a filter on your own. You could for example use `[BenchmarkCategory]` attribute and implement a filter similar to [AnyCategoriesFilter](https://github.com/dotnet/BenchmarkDotNet/blob/master/src/BenchmarkDotNet/Filters/AnyCategoriesFilter.cs).

More examples:

https://github.com/dotnet/performance/blob/main/src/harness/BenchmarkDotNet.Extensions/PartitionFilter.cs
https://github.com/dotnet/performance/blob/main/src/harness/BenchmarkDotNet.Extensions/ExclusionFilter.cs

Since this is by design and it's already complex and I don't believe that introducing another attribute to BDN would help I am going to close the issue. Thanks!

**Closed by adamsitnik** 2021-12-16 09:16 UTC

**Comment by glen-nicol** [comment] 2021-12-20 20:06
That's reasonable. I wasn't aware of those filter capabilities. Thanks!
