### ISSUE TITLE
Custom results table columns

### ISSUE THREAD

**Issue by timcassell** [dotnet/BenchmarkDotNet#1730] opened 2021-06-20 02:11 UTC
It would be useful to be able to output custom values to the results table.

I was thinking it could be done by utilizing a method returning a `Dictionary<string, string>` with a new attribute that is called as the final thing before `GlobalCleanup`.

```cs
public class Benchmark
{
    [Benchmark]
    public void MyBenchmark
    {
        // ...
    }
    
    [Benchmark]
    public void MyBenchmark2
    {
        // ...
    }
    
    [CustomTableResults(Target = nameof(MyBenchmark))]
    public Dictionary<string, string> GetCustomResults()
    {
        return new Dictionary<string, string>()
        {
            ["Example Result"] = "Custom result for " + nameof(MyBenchmark)
        };
    }
}
```

Would output like this:

```
|       Method |     Mean |     Error |    StdDev |                Example Result |
|------------- |---------:|----------:|----------:|------------------------------:|
|  MyBenchmark | 1.368 ns | 0.0038 ns | 0.0032 ns | Custom result for MyBenchmark |
|------------- |----------|-----------|-----------|-------------------------------|
| MyBenchmark2 | 1.364 ns | 0.0094 ns | 0.0083 ns |                             - |
```

Results could be calculated after the benchmark runs inside the method, or calculated in `GlobalSetup`, cached, and read in that method. It's quite versatile. The fact that it's a dictionary prevents duplicate keys (though some care would need to be taken concerning existing column names).

The only downside I see is if the strings get really long, but that should only be a concern for the developer.

**Comment by adamsitnik** [comment] 2021-06-21 07:21
Hi @timcassell 

this is a duplicate of https://github.com/dotnet/BenchmarkDotNet/issues/784, please post your idea there

**Closed by adamsitnik** 2021-06-21 07:21 UTC
