### ISSUE TITLE
Found conflicts between different versions of "System.CodeDom" that could not be resolved

### ISSUE THREAD

**Issue by JohnNilsson** [dotnet/BenchmarkDotNet#1368] opened 2020-02-02 01:12 UTC
I get this warning in a BenchmarkDotNet-project (net471)

>Warning	MSB3277	Found conflicts between different versions of "System.CodeDom" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.

```
There was a conflict between System.CodeDom, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 and System.CodeDom, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51.
    "System.CodeDom, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" was chosen because it was primary and "System.CodeDom, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" was not.
    References which depend on "System.CodeDom, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" [C:\Users\johnn\.nuget\packages\system.codedom\4.4.0\ref\net461\System.CodeDom.dll].
        C:\Users\johnn\.nuget\packages\system.codedom\4.4.0\ref\net461\System.CodeDom.dll
            Project file item includes which caused reference "C:\Users\johnn\.nuget\packages\system.codedom\4.4.0\ref\net461\System.CodeDom.dll".
                C:\Users\johnn\.nuget\packages\system.codedom\4.4.0\ref\net461\System.CodeDom.dll
    References which depend on "System.CodeDom, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" [].
        C:\Users\johnn\.nuget\packages\benchmarkdotnet\0.12.0\lib\netstandard2.0\BenchmarkDotNet.dll
            Project file item includes which caused reference "C:\Users\johnn\.nuget\packages\benchmarkdotnet\0.12.0\lib\netstandard2.0\BenchmarkDotNet.dll".
                C:\Users\johnn\.nuget\packages\benchmarkdotnet\0.12.0\lib\netstandard2.0\BenchmarkDotNet.dll
                C:\Users\johnn\.nuget\packages\benchmarkdotnet.diagnostics.windows\0.12.0\lib\netstandard2.0\BenchmarkDotNet.Diagnostics.Windows.dll
```
The System.CodeDom 4.4.0 package is brought in as a dependency by Microsoft.ML 1.4.0

Not sure how to resolve this. Haven't found a way to override dependencies on my end. Should something change in BenchmarkDotNet perhaps, to make System.CodeDom an explicit dependency?

**Comment by adamsitnik** [comment] 2020-02-03 11:16
Hi @JohnNilsson 

I see this error for the first time.

Could you please try to force the update of `System.CodeDom` used by your project?

```xml
<PackageReference Update="System.CodeDom" Version="4.7.0" />
```

**Comment by JohnNilsson** [comment] 2020-02-03 22:21
I'm afraid that didn't work.

Also, tried more TargetFramework same results for net461 and net480, no warning for netcoreapp3.1 or netcoreapp2.1 (might [this](https://github.com/dotnet/source-build/issues/738) be an indication that the dll was accidentally included in sdks?)

```csproj
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net471</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.12.0" />
    <PackageReference Include="Microsoft.ML" Version="1.4.0" />
    <PackageReference Update="System.CodeDom" Version="4.7.0" />
  </ItemGroup>

</Project>
```

```
PS C:\dev\bench> dotnet build --nologo
  Restore completed in 32,24 ms for C:\dev\bench\bench.csproj.
C:\Program Files\dotnet\sdk\3.1.101\Microsoft.Common.CurrentVersion.targets(2106,5): warning MSB3277: Found conflicts between different versions of "System.CodeDom" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed. [C:\dev\bench\bench.csproj]
  bench -> C:\dev\bench\bin\Debug\net471\bench.exe
```

besides the warning (from binlog)
```
There was a conflict between System.CodeDom, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 and System.CodeDom, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51.
    "System.CodeDom, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" was chosen because it was primary and "System.CodeDom, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" was not.
    References which depend on "System.CodeDom, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" [C:\Users\johnn\.nuget\packages\system.codedom\4.4.0\ref\net461\System.CodeDom.dll].
        C:\Users\johnn\.nuget\packages\system.codedom\4.4.0\ref\net461\System.CodeDom.dll
            Project file item includes which caused reference "C:\Users\johnn\.nuget\packages\system.codedom\4.4.0\ref\net461\System.CodeDom.dll".
                C:\Users\johnn\.nuget\packages\system.codedom\4.4.0\ref\net461\System.CodeDom.dll
    References which depend on "System.CodeDom, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" [].
        C:\Users\johnn\.nuget\packages\benchmarkdotnet\0.12.0\lib\netstandard2.0\BenchmarkDotNet.dll
            Project file item includes which caused reference "C:\Users\johnn\.nuget\packages\benchmarkdotnet\0.12.0\lib\netstandard2.0\BenchmarkDotNet.dll".
                C:\Users\johnn\.nuget\packages\benchmarkdotnet\0.12.0\lib\netstandard2.0\BenchmarkDotNet.dll
```
there is also
```
Dependency System.CodeDom, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51.
    Could not resolve this reference. Could not locate the assembly "System.CodeDom, Version = 4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
    For SearchPath "{TargetFrameworkDirectory}".
        Considered "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\System.CodeDom.winmd", but it didn't exist.
        Considered "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\System.CodeDom.dll", but it didn't exist.
        Considered "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\System.CodeDom.exe", but it didn't exist.
        Considered "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.CodeDom.winmd", but it didn't exist.
        Considered "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.CodeDom.dll", but it didn't exist.
        Considered "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.1\Facades\System.CodeDom.exe", but it didn't exist.
    Required by "C:\Users\johnn\.nuget\packages\benchmarkdotnet\0.12.0\lib\netstandard2.0\BenchmarkDotNet.dll".
```

**Comment by adamsitnik** [comment] 2020-02-04 14:57
I was able to reproduce the warning, but everything works fine. 

@JohnNilsson are you able to run the benchmarks?

```log
1>------ Build started: Project: ConsoleApp37, Configuration: Debug Any CPU ------
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2081,5): warning MSB3277: Found conflicts between different versions of "System.CodeDom" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.
1>ConsoleApp37 -> C:\Users\adsitnik\source\repos\ConsoleApp37\bin\Debug\net471\ConsoleApp37.exe
1>Done building project "ConsoleApp37.csproj".
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
```

**Comment by JohnNilsson** [comment] 2020-02-04 15:58
Benchmarks works fine. And at least one System.CodeDom.dll is provided. No binding redirect though.
It's an annoyance due to the warning as error we use in a ci-build. Suppressed the warning with this for now. Would rather not have to do that.
```csproj
  <PropertyGroup>
    <MSBuildWarningsAsMessages>MSB3277</MSBuildWarningsAsMessages>
  </PropertyGroup>
```

**Comment by adamsitnik** [comment] 2020-02-04 17:57
@eerhardt do you know how we could get rid of this warning?

**Comment by eerhardt** [comment] 2020-02-05 00:15
There are a few things happening here that causes this issue to happen.

First, `BenchmarkDotNet` references `System.Management` v4.5.0. `System.Management` references `System.CodeDom` v4.5.0. But it only declares its dependency on `System.Code` if you are targeting .NET Core or .NET Standard. See [Dependencies here](https://www.nuget.org/packages/System.Management/4.5.0):

![image](https://user-images.githubusercontent.com/8291187/73798683-38eea400-4779-11ea-980a-59907841dd7d.png)

So when you are building for `net4xx`, `System.Management` (and thus `BenchmarkDotnet`) is not pulling in `System.CodeDom` v4.5.0 into the NuGet graph. 

The only `System.CodeDom` that is in the NuGet graph comes from `Microsoft.ML` in your .csproj above. Microsoft.ML references `System.CodeDom` v4.4.0, a version less than what `BenchmarkDotnet` transitively references through `System.Management`. When MSBuild is inspecting dependencies, it sees that you are referencing `BenchmarkDotnet`, which needs a newer version of `System.CodeDom` than what you are referencing, and thus the warning occurs.

To fix this in your .csproj, Include a reference to System.CodeDom 4.5.0 or higher. (Note: you have an `Update` above which won't work. MSBuild `Update` only works once someone before you has `Include`d it. But no one is including it in MSBuild.)

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net471</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.12.0" />
    <PackageReference Include="Microsoft.ML" Version="1.4.0" />
    <PackageReference Include="System.CodeDom" Version="4.5.0" />
  </ItemGroup>

</Project>
```

That builds cleanly with no warnings for me.

If we wanted to fix this in `BenchmarkDotNet`, the fix would be to lift the transitive reference for `System.CodeDom` directly into `BenchmarkDotNet` Nuget package. So that way people on .NET Framework will get `System.CodeDom` into the NuGet graph.

**Comment by JohnNilsson** [comment] 2020-02-05 11:13
Ah, 4.5.0, i only tested using Include with 4.4.0.
Confirmed, this works for me.

**Comment by adamsitnik** [comment] 2020-02-12 18:41
@eerhardt thanks for a great explanation and help!

@JohnNilsson I am closing this issue. If you feel that we should define this dependency in an explicit way, please send a PR that adds it.

**Closed by adamsitnik** 2020-02-12 18:41 UTC

**Comment by kkulkarniMS** [comment] 2022-10-25 17:05
I am getting the same warnings because of my Microsoft.ML nuget package related to System.CodeDom. Where do I update the package reference number? 

"Found conflicts between different versions of "System.CodeDom" that could not be resolved. There was a conflict between "System.CodeDom, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" and "System.CodeDom, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51". "System.CodeDom, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" was chosen because it was primary and "System.CodeDom, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" was not."
