### ISSUE TITLE
ArgumentsSource for large complex type

### ISSUE THREAD

**Issue by valentinoNguyen** [dotnet/BenchmarkDotNet#1272] opened 2019-10-04 01:42 UTC
Hi,

I want to generate a large amount of test input data to benchmark my query.
Basically I will combine predefined params into a large amount of test input:

` public IEnumerable<TestParam> Data() `
`{`
            `  var dimensions = new string[] { "A", "B" };`
           `   var kpis = new string[] { "C" };`
            `  parameters = CombineArray.generateParams(dimensions, kpis);`
           `   return parameters.AsEnumerable();`
`}`

Then use it as argumentSource of my benchmark ` [ArgumentsSource(nameof(Data))]`
The problem is eveytime benchmark method run, it again executes Data method, which can be slow if I try to put large amount of dimensions and kpis, it can generate million of test input.

I think I can put it on `GlobalSetup`, but don't know how to setup benchmark method to run all of the test input there.
Please help,
Thank you!!!

**Comment by adamsitnik** [comment] 2019-10-05 16:00
Hello @valentinoNguyen !

> The problem is eveytime benchmark method run, it again executes Data method, which can be slow if I try to put large amount of dimensions and kpis, it can generate million of test input.

This is unfortunately by design. We simply run something like `argumentSource().ToArray()[argumentIndex]` in the auto-generated code.

The good news is that as you said moving it to `[GlobalSetup]` should work:

```cs
[Params("A", "B")]
public string Dimension {get; set;}

[Params("C", "D")]
public string KPI { get; set;

private TestParam _testParam;

[GlobalSetup]
public void Setup() => _testParam = generateParams(Dimension, KPI);
``` 

The key thing here is that when you are using multiple `Params` in your type with benchmarks, BDN creates a cartesian product of all params. For the example above (ABxCD), we would have the following 4 benchmark cases:

* A, C
* A, D
* B, C
* B, D

**Comment by valentinoNguyen** [comment] 2019-10-06 04:07
Thank you for your quick response!
But I am curious if is there any way to allow `Params()` take a function or something to generate a set of input params instead of hardcode it like this.

**Comment by adamsitnik** [comment] 2019-10-06 09:12
> But I am curious if is there any way to allow Params() take a function or something to generate a set of input params instead of hardcode it like this.

Unfortunately not. The reason is that we need to run the benchmark in a separate process and things like functions are hard to serialize and deserialize (in our case the host and parent process can be two different runtimes: for example .NET Core and Mono or Full .NET Framework and .NET Core)

**Comment by adamsitnik** [comment] 2020-03-11 13:58
I am closing since the question got answered.

**Closed by adamsitnik** 2020-03-11 13:58 UTC
Labels: question
