### ISSUE TITLE
How to use [GenericTypeArguments]

### ISSUE THREAD

**Issue by dbogatov** [dotnet/BenchmarkDotNet#807] opened 2018-06-28 02:22 UTC
Hi everyone,

I have encountered a strange bug (`BenchmarkDotNet=v0.10.14.660-nightly`).

If I have the following:

```csharp
/// <typeparam name="C">Ciphertext type</typeparam>
/// <typeparam name="K">Key type</typeparam>
[MemoryDiagnoser]
[JsonExporterAttribute.Full]
[Orderer(SummaryOrderPolicy.FastestToSlowest)]
[RankColumn]
public class Benchmark<C, K>
	where C : IGetSize
	where K : IGetSize
{
	// some code here
}
```

attribute are not working.
Allocated column does not show up, no JSON file gets produced, columns are not ordered.

However, if I supply these the other way

```csharp
private class CustomConfig : ManualConfig
{
	public CustomConfig()
	{
		Add(MemoryDiagnoser.Default);
		Add(JsonExporter.Full);
		Add(DefaultConfig.Instance.GetLoggers().ToArray()); // manual config has no loggers by default
		Add(DefaultConfig.Instance.GetExporters().ToArray()); // manual config has no exporters by default
		Add(DefaultConfig.Instance.GetColumnProviders().ToArray()); // manual config has no columns by default
	}
}
```

everything works just fine.

P.S. That also applies to "GenericType" attribute.
I have to use 

```csharp
BenchmarkSwitcher.FromTypes(
	new[] {
		typeof(Schemes.Benchmark<OPECipher, BytesKey>),
		typeof(Schemes.Benchmark<ORESchemes.SchemOne.Ciphertext, BytesKey>),
		typeof(Schemes.Benchmark<ORESchemes.SchemeTwo.Ciphertext, ORESchemes.SchemeTwo.Key>),
		typeof(Schemes.Benchmark<ORESchemes.SchemeThree.Ciphertext, ORESchemes.SchemeThree.State>),
		typeof(Primitives.Benchmark)
	}
).Run(new[] { $"--namespace=Benchmark.{@namespace}", "--join" }, new CustomConfig());
```

**Comment by adamsitnik** [comment] 2018-06-28 10:55
@Rizzen could you take a look into this issue?

**Comment by Rizzen** [comment] 2018-06-28 13:59
Ok, I'll take a look today.

**Comment by Rizzen** [comment] 2018-06-28 20:28
@dbogatov Thank you for report!
So, I made some workaround and doesn't have repro. Here is my workaround:
``` C#
class Program
{
    static void Main(string[] args)
    {
        BenchmarkSwitcher.FromTypes(new Type[] { typeof(BenchmarkGeneric<,>) }).Run();
    }
}

[MemoryDiagnoser]
[JsonExporterAttribute.Full]
[Orderer(SummaryOrderPolicy.FastestToSlowest)]
[RankColumn]
[GenericTypeArguments(typeof(SizeTypeOne), typeof(SizeTypeTwo))]
public class BenchmarkGeneric<C, K>
        where C : IGetSize
        where K : IGetSize
{
    [Benchmark] public C CreateC() => Activator.CreateInstance<C>();

    [Benchmark] public K CreateK() => Activator.CreateInstance<K>();
}

public interface IGetSize
{
        
}

public class SizeTypeOne : IGetSize {}
public class SizeTypeTwo : IGetSize {}
```
It works fine as far I see.
Did you use GenericTypeArguments Attribute? Could you provide more detailed repro?

@adamsitnik @AndreyAkinshin Also I see that there is no Intro for GenericTypeArguments. So I think that is makes sense to add it. What do you think?

**Comment by adamsitnik** [comment] 2018-06-28 20:33
> So I think that is makes sense to add it. What do you think

Great idea!

**Comment by Rizzen** [comment] 2018-06-28 20:42
Aww, sorry, it exists in IntroGenericTypeArguments.cs

**Comment by dbogatov** [comment] 2018-06-28 20:44
It does, but could you also mention it in docs?

I will try to come up with MWE for the issue.
Thank you for prompt replies!

Also, am I right that this feature is not in release yet?
I am using nightly build.

**Comment by dbogatov** [comment] 2018-06-28 20:49
At least it will appear in release docs.
That it good enough for me.

**Comment by adamsitnik** [comment] 2018-07-09 10:22
@Rizzen was unable to reproduce, @dbogatov did not provide repro for 11 days so I am closing

**Closed by adamsitnik** 2018-07-09 10:22 UTC
Labels: question

**Comment by dbogatov** [comment] 2018-07-09 10:29
My bad, I am on a conference now. 
Let me reopen the issue when (and if) repro is ready.
